### ISSUE TITLE
Optional email reminders 

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#100]
Users have been asking for daily check-in reminders, and it would increase engagement. For now I believe it is not too expensive to do it by email, since we cannot do push notifications.

- [x] Add to onboarding process
- [x] Add option in settings to stop the reminders
- [x] Send reminder email at user's selected time with a "stop reminder" unsubscribe link
- [x] Add time zone for user
- [x] Searchable dropdown for time zone
- [x] Add card 'Notifications'
- [x] Fix reminder bug
- [x] Set default time zone

Right before "onboarding complete" step:
<img width="865" alt="screenshot 2017-08-21 12 20 54" src="https://user-images.githubusercontent.com/1657444/29528882-9d80e652-866b-11e7-84a2-4aa15c1b718c.png">

**Comment by mpugach** [comment]
Add an email mockup please

**Comment by lmerriam** [comment]
Hold on this one

**Comment by lmerriam** [comment]
@X-tina you can make a barebones email and let me style it, I will do it alongside the weekly digest email.
