### ISSUE TITLE
Pushing production data to data science DB

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#101]
We have a data science API that @Graydyn has created. To set it up, we ran a rake task to generate a CSV (we had to take the production app offline to do this) which graydyn was able to use.

I'd like to set it up so that we can periodically push new data from our production DB to our data science API. @mpugach do you have an idea of how much effort this task would take? You can consult with @Graydyn for the details of his database.

**Comment by mpugach** [comment]
@Graydyn hi, do you execute `rake utils:csv_export` for this?

Why is offline needed? Is it about heroku limits or data consistency?

**Comment by Graydyn** [comment]
I don't do the exports, talk to algodave in Slack.

**Comment by lmerriam** [comment]
@algodave is that the correct rake task? It looks right.

@mpugach as I understand it, the potential benefit of a separate DB is that the data scientists can have their own sandbox to create endpoints for their needs. Particularly in the future if we need to calculate more complex stats like correlations or user similarity and we want to crunch them on a server running Python or R or another more data-science-friendly environment. ( @Graydyn correct me if I'm off base there)

There are two use cases for this API. One is for research purposes -- researchers who want to look at our data as part of an investigation can use these endpoints. The second is for in-app features like #128 which @jaredgalanis is starting work on right now.

Max/gradyn/davide/jared: would like to hear your input. Should we continue to use a separate data science API or should we migrate endpoints that will be used in the app to the production API? What are the pros/cons?

**Comment by Graydyn** [comment]
I don't know much about your prod environment, but as long as you can install pandas on it then moving the endpoints should be easy enough. Maybe setup a cron job to generate the statistics during the night and cache them? The code to generate the stats can be copied out of my notebooks. And if you can't run pandas, porting the code over to JavaScript or whatever you're using shouldn't be too bad, there is nothing terribly complicated going on there.

**Comment by mpugach** [comment]
The pandas can be installed as a separate heroku app, which can be connected to the mongodb to consume user trackings.

It is not clear what output it should produce to be accessible by the public.

**Comment by lmerriam** [comment]
R is also popular for data science, Peer has written some stuff we'd like to use for the app which uses R libraries. @Graydyn how do you think we should deal with multiple data scientists working in different languages? Is it desirable to run multiple environments or should we translate everything into one language?

**Comment by Graydyn** [comment]
I don't think you'll ever need to run R in prod. You could get Peer's opinion on that too, but R is more for an academic environment. There are people out there running Shiny apps in the real world, but in the long run it will probably be easier on Peer to convert to Python than try and productionalize and webifiy his R code.

**Comment by lmerriam** [comment]
@Graydyn thanks for the feedback. I think Peer has specific knowledge of R so we all might need to get together and translate. At least for now it's pretty simple -- very similar to the treatment effect stuff you had written earlier.

@mpugach for context there are two main places we'd want to use it:

1. As part of the history we want to build some personal analytics for the user. For example we would like to look at all of a user's conditions and calculate how they correlated with every treatment/tag/food/weather trackable they have tracked, then show the user the strongest correlations.
2. As part of the new "explore" section, we'd also want to show these same correlations across all users. So we'd look at a condition and calculate how it correlates with a .

Right now it entails looking at the difference in average severity of a condition on days when tracking the related tag/treatment/etc trackable, vs on days when the user did not track the related trackable. I believe we'll have more complex math to do in the future. I hope I'm explaining this well enough, let me know.

**Comment by mpugach** [comment]
Because the data needs to be accessed by the app, there is no benefit in a separate DB.

Since it looks like a denormalized reports (no relations needed) we can utilize existing MongoDB to store this.

So I think of the following flow:
[Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler) or our [own custom clock process](https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes) (last one is preferable [according to the docs](https://devcenter.heroku.com/articles/scheduler#known-issues-and-alternatives)) starts a [background job](https://devcenter.heroku.com/articles/background-jobs-queueing). Which reads and outputs the data from and into MongoDB. Background job can be implemented in Python, so only DB connection logic needs to be added to @Graydyn`s scripts.

**Comment by lmerriam** [comment]
This sounds like the right approach to me
