### ISSUE TITLE
Weather API

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#104]
We've had an incredible amount of requests for weather tracking.

Possible API: http://www.openweathermap.com/price

Ideal behavior: when the user goes to any check-in at any point in time they see weather data and in their charts there is a complete history of the weather over time in their area. The weather data for a given day would appear in the check-in summary.

Proposed behavior for fewer API calls: when the user checks-in on the current day or within the time period that the API license grants, we get the weather data and add it to the user's check-in and chart just for that day. It would appear in the summary of the check-in.

In the summary:
![fd_weather_in_summary](https://cloud.githubusercontent.com/assets/1657444/20699978/846c09a8-b5d8-11e6-81f1-d2ae47614521.png)

Data to pull in would be high/low temperature, humidity, and description (cloudy, sunny, rainy, etc). This will may depend on the API we end up using.

We'll need to ask the user to add a zip code to their account for this, or guess their area from IP location, which is probably accurate enough for weather.

**Comment by lmerriam** [comment]
Jared pointed out the api at https://darksky.net/dev/ which looks like it might be the best option.

**Comment by mpugach** [comment]
@lmerriam 

Location on IP is the easiest to implement. But there can be cases when the client is located behind some Network Address Translation (corporate networks, VPNs, China government restrictions and smart Chinese :) ) so it will not be accurate enough for some cases.

We can also ask browser location service. In this case we need the user's permission. It uses GPS if available, WiFi triangulation or asks the user to input the location manually. It is browser's responsibility and cannot be controlled.
Do not know if it performs fallback to IP geolocation, but we can do it on backend if user didn't gave the permission or there are some errors.

Also we can hide the weather and print some message, if the user do not want to give the location permission.

My proposition is to require some action on the weather widget: "In order to get the weather we need your location. Blah blah blah..." and "Get weather" button which fires the browser location API. If there were errors then try the IP way.

1. We need icons for the following states:`clear-day`, `clear-night`, `rain`, `snow`, `sleet`, `wind`, `fog`, `cloudy`, `partly-cloudy-day`, `partly-cloudy-night` and some default one in case DarkSky adds new state.
2. Can you provide mockups for checkin and chart views please?
3. If user moved to another location and wants to check in for yesterday should we concern about it?

**Comment by lmerriam** [comment]
@mpugach I think we should show an "empty" state asking the user to enter their postal code -- I believe they will like this better than if we guess for them due to privacy. This should appear right below the "notes" in the summary screen.

The user should be able to change their location as well, by clicking the postal code.

Because I don't want to overload the charts with weather, I believe we can show just pressure, humidity, and temperature.

However I am curious how we should do this considering these numbers change over the course of the day. It appears Darksky has a concept of "daily" observations, but I assume we can't get today's observation until the day is over -- do we need to run a job at the end of each day to fill in the weather for every checkin that has requested it? What do you think?

Mocks are below. I will work on illustrations for the weather states, we can use placeholders in the meantime.

<img width="946" alt="screenshot 2016-12-14 17 43 18" src="https://cloud.githubusercontent.com/assets/1657444/21204866/585170b4-c227-11e6-927b-9de9b84b6c4b.png">

**Comment by mpugach** [comment]
"daily'' observation for the current day is available during the day. But I do not know if they make corrections. In case of issue we can implement background job to update it in the end of the day.

**Comment by mpugach** [comment]
@lmerriam 

How the weather states illustrations going?

There are `temperatureMin` and `temperatureMax` but no `temperature` for daily. How should the chart look like?

**Comment by mpugach** [comment]
@lmerriam  see this on staging
used my forecast API key

**Comment by lmerriam** [comment]
It's looking really good!

It appears to be getting tomorrow's forecast on today's check-in. If I go to my summary today I see this:
<img width="520" alt="screenshot 2016-12-28 13 14 27" src="https://cloud.githubusercontent.com/assets/1657444/21528772/ed663212-cd02-11e6-8143-a0fdcfccafdb.png">

But it's not supposed to rain today according to Dark Sky. It _is_ supposed to rain tomorrow however:
<img width="1440" alt="screenshot 2016-12-28 13 39 07" src="https://cloud.githubusercontent.com/assets/1657444/21528788/0a2bc2d6-cd03-11e6-9775-a83d373a01fc.png">

Other changes:
- We should round to whole numbers for all measurements
- It looks like the label for Pressure should be "mb" as that is what dark sky uses. I used "in" in the mockup, my mistake. Also I see numbers in the 1000's for today and tomorrow on darksky, so I'm not sure where the 29.9 number on my check-in comes from.
- Humidity needs to be converted to a percent (multiply by 100, it should be 77% here)

Which number are you pulling for "precipitation" here? In the api docs I see "precipIntensity", "precipProbability" etc

**Comment by mpugach** [comment]
pressure is converted using [this formula](https://www.reference.com/science/formula-convert-millibars-inches-45d1136c4c9a2284)

**Comment by mpugach** [comment]
There was an issue. The date was converted to time in UTC and then to Unix timestamp to send it to forecast API. Now it is converted to location's timezone first and then to timestamp.
It is fixed on staging, so please test.

**Comment by mpugach** [comment]
"precipIntensity" is used

**Comment by mpugach** [comment]
this is also deployed to staging, the changes are applied only to new forecasts

you can change postal code to trigger new forecast check, it was no cached before

**Comment by lmerriam** [comment]
@mpugach i'm sorry, I misunderstood the pressure conversion. As far as I can tell both are used but they are preferred in different locales, similar to fahrenheit/celsius.

How much effort do you think it would take to allow the user to change units of measurement (presentationally) between `°f / °c` for temperature and `mbar / inhg` for pressure? The user could click a button to open a form and choose units, or click on the units themselves, whichever is easier. I don't think it's worth it if it will take more than a few hrs.

Otherwise this seems to work very well for me and looks great!

**Comment by mpugach** [comment]
ok
we will save his preferences in profile and will adjust charts too
click on units with a pointer on hover is faster
it will take few hours

**Comment by lmerriam** [comment]
Sounds good, let's give these units an underline in the weather card to indicate that they can be changed.

**Comment by mpugach** [comment]
deployed to staging

**Comment by lmerriam** [comment]
Strange to see something like "Partly Cloudy Night" for my daily weather, do you know how the API picks a time to sample from? I opened this check-in at ~4pm.

![image](https://cloud.githubusercontent.com/assets/1657444/21579340/b3c2de12-cf77-11e6-8cb6-c9076b093fd6.png)

Is it possible to user precipAccumulation, or is that only available for time machine requests? If we can't use accumulation, let's at least label the precipitation intensity with `mm/hr`. And I believe we can get rid of the leading 0 before the decimal.

We should leave 2 decimal points for **pressure in inches**. Sorry for going back on that one, I didn't understand the unit earlier when we talked about rounding.

**Comment by mpugach** [comment]
> precipAccumulation optional, only on hourly and daily
> The amount of **snowfall** accumulation expected to occur, in inches. (**If no snowfall is expected, this property will not be defined.**)

**Comment by mpugach** [comment]
here are some API responses

for last response the **currently** and **daily** timestamps are same, but **precipIntensity** differs. I think it is in scope of whole day.

also see the icon for **currently** and **daily**. Daily timestamp is always midnight but icon sometimes is "partly-cloudy-day". Seems we need to show same summary (from the payload) to the user to make more sense. Currently we show humanized icon text.

here is [online timestamp convertor](http://www.onlineconversion.com/unix_time.htm) if you need

---

Checked at **Tue, 03 Jan 2017 07:12:55 EST -05:00** and **11206** postal code

For **Wed, 04 Jan 2017 01:00:00 EST -05:00**
```ruby
{"latitude"=>40.7047738,
 "longitude"=>-73.9418603,
 "timezone"=>"America/New_York",
 "offset"=>-5,
 "currently"=>
  {"time"=>1483509600,
   "summary"=>"Drizzle",
   "icon"=>"rain",
   "precipIntensity"=>0.0111,
   "precipProbability"=>0.45,
   "precipType"=>"rain",
   "temperature"=>44.48,
   "apparentTemperature"=>41.58,
   "dewPoint"=>42.61,
   "humidity"=>0.93,
   "windSpeed"=>5.23,
   "windBearing"=>255,
   "visibility"=>5.28,
   "cloudCover"=>0.99,
   "pressure"=>997.96,
   "ozone"=>292.95},
 "daily"=>
  {"data"=>
    [{"time"=>1483506000,
      "summary"=>"Mostly cloudy until afternoon.",
      "icon"=>"partly-cloudy-day",
      "sunriseTime"=>1483532469,
      "sunsetTime"=>1483566167,
      "moonPhase"=>0.21,
      "precipIntensity"=>0.0017,
      "precipIntensityMax"=>0.0111,
      "precipIntensityMaxTime"=>1483509600,
      "precipProbability"=>0.45,
      "precipType"=>"rain",
      "temperatureMin"=>32.11,
      "temperatureMinTime"=>1483588800,
      "temperatureMax"=>48.84,
      "temperatureMaxTime"=>1483556400,
      "apparentTemperatureMin"=>20.86,
      "apparentTemperatureMinTime"=>1483588800,
      "apparentTemperatureMax"=>43.67,
      "apparentTemperatureMaxTime"=>1483556400,
      "dewPoint"=>36.48,
      "humidity"=>0.79,
      "windSpeed"=>12.11,
      "windBearing"=>250,
      "visibility"=>8.61,
      "cloudCover"=>0.56,
      "pressure"=>1000.6,
      "ozone"=>309.06}]}}
```

For **Sun, 01 Jan 2017 01:00:00 EST -05:00**
```ruby
{"latitude"=>40.7047738,
 "longitude"=>-73.9418603,
 "timezone"=>"America/New_York",
 "offset"=>-5,
 "currently"=>
  {"time"=>1483250400,
   "summary"=>"Overcast",
   "icon"=>"cloudy",
   "precipIntensity"=>0.0014,
   "precipProbability"=>0.03,
   "precipType"=>"rain",
   "temperature"=>43.94,
   "apparentTemperature"=>40.8,
   "dewPoint"=>29.63,
   "humidity"=>0.57,
   "windSpeed"=>5.45,
   "windBearing"=>217,
   "visibility"=>10,
   "cloudCover"=>1,
   "pressure"=>1012.33,
   "ozone"=>301.7},
 "daily"=>
  {"data"=>
    [{"time"=>1483246800,
      "summary"=>"Partly cloudy overnight.",
      "icon"=>"partly-cloudy-night",
      "sunriseTime"=>1483273263,
      "sunsetTime"=>1483306811,
      "moonPhase"=>0.11,
      "precipIntensity"=>0.0002,
      "precipIntensityMax"=>0.0017,
      "precipIntensityMaxTime"=>1483246800,
      "precipProbability"=>0.04,
      "precipType"=>"rain",
      "temperatureMin"=>39.93,
      "temperatureMinTime"=>1483329600,
      "temperatureMax"=>47.93,
      "temperatureMaxTime"=>1483293600,
      "apparentTemperatureMin"=>39.3,
      "apparentTemperatureMinTime"=>1483261200,
      "apparentTemperatureMax"=>45.28,
      "apparentTemperatureMaxTime"=>1483293600,
      "dewPoint"=>27.28,
      "humidity"=>0.52,
      "windSpeed"=>3.13,
      "windBearing"=>273,
      "visibility"=>10,
      "cloudCover"=>0.22,
      "pressure"=>1020.55,
      "ozone"=>285.01}]}}
```

For **Sat, 31 Dec 2016 01:00:00 EST -05:00**
```ruby
{"latitude"=>40.7047738,
 "longitude"=>-73.9418603,
 "timezone"=>"America/New_York",
 "offset"=>-5,
 "currently"=>
  {"time"=>1483164000,
   "summary"=>"Clear",
   "icon"=>"clear-night",
   "precipIntensity"=>0,
   "precipProbability"=>0,
   "temperature"=>32.81,
   "apparentTemperature"=>25.88,
   "dewPoint"=>22.73,
   "humidity"=>0.66,
   "windSpeed"=>7.92,
   "windBearing"=>254,
   "visibility"=>10,
   "cloudCover"=>0,
   "pressure"=>1016.78,
   "ozone"=>362.2},
 "daily"=>
  {"data"=>
    [{"time"=>1483160400,
      "summary"=>"Mostly cloudy throughout the day.",
      "icon"=>"partly-cloudy-night",
      "sunriseTime"=>1483186856,
      "sunsetTime"=>1483220362,
      "moonPhase"=>0.08,
      "precipIntensity"=>0.0003,
      "precipIntensityMax"=>0.0022,
      "precipIntensityMaxTime"=>1483239600,
      "precipProbability"=>0.06,
      "precipType"=>"rain",
      "temperatureMin"=>30.81,
      "temperatureMinTime"=>1483178400,
      "temperatureMax"=>41.88,
      "temperatureMaxTime"=>1483221600,
      "apparentTemperatureMin"=>23.88,
      "apparentTemperatureMinTime"=>1483174800,
      "apparentTemperatureMax"=>34.81,
      "apparentTemperatureMaxTime"=>1483221600,
      "dewPoint"=>25.42,
      "humidity"=>0.63,
      "windSpeed"=>8.48,
      "windBearing"=>203,
      "visibility"=>10,
      "cloudCover"=>0.45,
      "pressure"=>1017.29,
      "ozone"=>333.42}]}}
```

For **Fri, 30 Dec 2016 00:00:00 EST -05:00**

```ruby
{"latitude"=>40.7047738,
 "longitude"=>-73.9418603,
 "timezone"=>"America/New_York",
 "offset"=>-5,
 "currently"=>
  {"time"=>1483074000,
   "summary"=>"Clear",
   "icon"=>"clear-night",
   "precipIntensity"=>0,
   "precipProbability"=>0,
   "temperature"=>36.55,
   "apparentTemperature"=>30.02,
   "dewPoint"=>29.37,
   "humidity"=>0.75,
   "windSpeed"=>8.68,
   "windBearing"=>250,
   "visibility"=>9.4,
   "cloudCover"=>0.08,
   "pressure"=>1001.5,
   "ozone"=>345.23},
 "daily"=>
  {"data"=>
    [{"time"=>1483074000,
      "summary"=>"Partly cloudy starting in the afternoon, continuing until evening.",
      "icon"=>"partly-cloudy-day",
      "sunriseTime"=>1483100447,
      "sunsetTime"=>1483133915,
      "moonPhase"=>0.04,
      "precipIntensity"=>0.0002,
      "precipIntensityMax"=>0.0013,
      "precipIntensityMaxTime"=>1483135200,
      "precipProbability"=>0.02,
      "precipType"=>"rain",
      "temperatureMin"=>33.64,
      "temperatureMinTime"=>1483156800,
      "temperatureMax"=>40.32,
      "temperatureMaxTime"=>1483120800,
      "apparentTemperatureMin"=>25.75,
      "apparentTemperatureMinTime"=>1483156800,
      "apparentTemperatureMax"=>32.67,
      "apparentTemperatureMaxTime"=>1483120800,
      "dewPoint"=>26.81,
      "humidity"=>0.68,
      "windSpeed"=>10.1,
      "windBearing"=>256,
      "visibility"=>9.51,
      "cloudCover"=>0.14,
      "pressure"=>1005.94,
      "ozone"=>365.09}]}}
```

**Comment by mpugach** [comment]
deployed to staging

**Comment by lmerriam** [comment]
This looks excellent! I am happy to deploy. Nice work.

**Comment by mpugach** [comment]
thanks
