### ISSUE TITLE
New trackable types

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#106]

**Comment by algodave** [comment]
Examples (shared by @lmerriam)

<img width="238" alt="screenshot 2016-09-07 16 32 55" src="https://cloud.githubusercontent.com/assets/2955556/18327543/57af0a5a-754b-11e6-9796-5f5a6b340d75.png">

**Comment by lmerriam** [comment]
some examples of new inputs for trackables that we’d build are `time` (example: I went to bed at 8:00pm), `number` with an optional `unit` (example: my temperature was 98° fahrenheit), `select`dropdown (example: my stool was soft/solid/watery)

**Comment by lmerriam** [comment]
Mockup of the process to choose a trackable type when adding a trackable

<img width="857" alt="screenshot 2016-09-29 21 38 01" src="https://cloud.githubusercontent.com/assets/1657444/18978975/1bd0f8f8-8695-11e6-9b69-e744dea6c861.png">

**Comment by algodave** [comment]
@lmerriam I'm thinking: if we allow users to track their own custom things, each one with a custom set of values, we would loose the ability to compare those data across different users. 

Following the example in your mockups: 
- one user could track "Abdominal Pain" with values "Low", "Medium", "High"; 
- another user could track "Abdominal Ache" with values "Short with low intensity", "Short with high intensity", "Long with low intensity", "Long with high intensity"

The system then won't be able to understand that we're talking about the same thing!
The data science part would then loose an opportunity to make statistical inference and provide interesting insights to clinics' physicians.

Just thinking aloud...

**Comment by lmerriam** [comment]
I had the exact same concern, you are absolutely right that it will fragment the data. I thought it would be a big problem so I talked to the data scientists before making the tickets, but they both agreed that it will probably get us more data, and even if they have to do more work or ignore some data it's worthwhile.

What if we forget about the `select from options` input. That one is less important than the `number+unit` and `time`, and will also cause much more variation than the other two. Do you think that will help?

**Comment by algodave** [comment]
Totally agree, I was going to suggest that same thing

Il 05/ott/2016 23:57, "Logan" notifications@github.com ha scritto:
