### ISSUE TITLE
Allow user to track food

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#108]
Food is extremely important to all illnesses, and our users have asked to be able to track it many times. We would like to allow them to track the foods they eat each day so they can be related to their symptoms.

We will rename the "Tags" section of the check-in to "Health factors", and include a place to log food in that screen:
![fd_food_tracker](https://cloud.githubusercontent.com/assets/1657444/20876001/f220fd24-ba8c-11e6-8435-c0d561aa46cf.png)

![image](https://cloud.githubusercontent.com/assets/1657444/20876070/5ba49936-ba8d-11e6-9624-194a680d6bd5.png)
User flow:
- User clicks "add food" input
- Before user starts typing, they see a dropdown list with random popular food items
- User starts typing and sees autocomplete results based on the current input
- User selects a food from the list OR creates a new food
- The food item is logged for the day and is displayed above the "add food" input
- Clicking the food item removes it from the check-in
*All of this behavior already exists in the "Tags" section of the same screen, refer to its components for the specific logic.*

Non-goals:
Displaying nutrients
Displaying food groups
Tracking portions

Databases
The [USDA food database](https://ndb.nal.usda.gov/ndb/doc/) is a very promising (and free) option.
I have a data.gov API key for this. It is also possible to [download the whole DB](https://www.ars.usda.gov/northeast-area/beltsville-md/beltsville-human-nutrition-research-center/nutrient-data-laboratory/docs/usda-national-nutrient-database-for-standard-reference/) which might be necessary for the autocomplete results. We should retain the IDs in case we need to look up the nutrients and food groups in the future.

**Comment by lmerriam** [comment]
Max, please ask @algodave and @safeforge for specific technical questions. I have the first one: how should we store and reference this food data?

**Comment by mpugach** [comment]
the issue number inspires me to say "namaste" :pray:

@algodave, @safeforge there are some tests failing on my local. One in backend and 10 in frontend. Is it Ok?

Should we add Travis integration to the PRs? It is forever free for open source

**Comment by safeforge** [comment]
@mpugach I've pushed [4e7536c ] which fix backend's specs.

**Comment by mpugach** [comment]
@safeforge thanks!

@lmerriam I'm going to store food descriptions in PG. It will behave the same as tags:
1. refer to PG id from Mongo document
2. utilize "globalize" gem to store localizations in PG

I assume that we should allow users to enter new food items. So we will not override the PG table primary key with original USDA id, but keep it in a separate field instead.

Also I'm going to add 1.5Mb ASCII file to fixtures (USDA food descriptions) and implement rake task to load it into DB.

@algodave, @safeforge what do you think?

**Comment by algodave** [comment]
@mpugach Agree on everything! Just a note: food records from the USDA db should be saved with `en` translations which is our default locale.

**Comment by mpugach** [comment]
@lmerriam deployed to prod
