### ISSUE TITLE
Timestamped trackables

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#109]
Our #1 user request of all time: record a given trackable at different times in one day
<img width="1328" alt="screenshot 2016-09-05 01 41 18" src="https://cloud.githubusercontent.com/assets/1657444/18238330/ea626fde-7309-11e6-8c2e-c9bab8cc86b5.png">

Clicking the "x" next to a rating would remove that particular rating
If there is only one rating (with a time) clicking the "x" would turn it back to "all day"

Note that "rate again" doesn't appear until the user chooses a time for the first rating -- it would be confusing for us to have an "all day" rating alongside time-specific ones in a single day

In the case of treatments, we would be adding doses instead of ratings. When the user turns on a treatment it should autofill with all doses from the previous day (the same way we auto-complete now)

Regarding the chart: since it's on a timescale we can display each of these ratings, or we can get the average for each day and show only one rating per day as we do now.

**Comment by lmerriam** [comment]
<img width="371" alt="screenshot 2016-09-07 16 47 36" src="https://cloud.githubusercontent.com/assets/1657444/18327957/d4c04134-751a-11e6-80e3-c3fc2e2b228e.png">

**Comment by lmerriam** [comment]
<img width="343" alt="screenshot 2016-09-07 16 50 45" src="https://cloud.githubusercontent.com/assets/1657444/18328087/55a1845c-751b-11e6-89ae-ded96689a7d5.png">

@algodave also I want to clarify (because my mocks confused the mobile devs) that the idea is to submit additional ratings for a given trackable -- and not to have, for example, a 9:00 check-in and a 1:00 check-in

**Comment by lmerriam** [comment]
http://amsul.ca/pickadate.js/time/ looks like the best mobile UI for timepicking, and the accompanying pickadate plugin will be useful for #17 and other places where we want to do date selection

**Comment by lmerriam** [comment]
Slight update to the design, I think it will make it less likely that the user accidentally rates a symptom or taps into the dose input

<img width="451" alt="screenshot 2016-09-27 22 52 22" src="https://cloud.githubusercontent.com/assets/1657444/18899326/12952b32-8506-11e6-83ff-785f3e72b5e4.png">
<img width="446" alt="screenshot 2016-09-27 22 59 53" src="https://cloud.githubusercontent.com/assets/1657444/18899328/1f539a98-8506-11e6-83a8-00a3f95aafbf.png">

**Comment by algodave** [comment]
@lmerriam How should these be represented in the chart? We have one tick per day in the chart's x-axis

**Comment by lmerriam** [comment]
There are a few ways that I can think of. Do either of the following work better for you guys?

1) The x-axis already represents time, we could "unlock" it from a daily check-in and let the points fall at their respective times.

2) We could store an "average" score for the day and graph that the same as we are graphing the single daily value on the chart currently. I like this somewhat better, as it won't get cramped with lots of points and the averaging might actually be helpful to people. But I understand we'd have to be saving and updating averages in the background.

If there are other ideas you have, I'd love to hear them!

**Comment by algodave** [comment]
I like the idea of avg values for trackables who are rated on a 0-4 scale, whereas for treatments I would still show one marker icon when taken, and when the user clicks on it the tooltip would show all doses with times, one per line

**Comment by lmerriam** [comment]
Yes! That sounds perfect 👍

**Comment by algodave** [comment]
@lmerriam In the latest designs the 'x' to remove a rating disappeared, I guess you don't want to loose that feature though?

**Comment by lmerriam** [comment]
@algodave oh yes I forgot to mention that! I was hoping we could find a way to move that ability to the time select -- one of the time options would be "Remove rating". I don't know how feasible that is. It would be very helpful because otherwise we have a bunch of "x" all over the page and it's tough to give them enough space.

We should still have the 'x' to remove the trackable though, that was an oversight.

**Comment by algodave** [comment]
@lmerriam I won't have time for this in the current month, I only started with some backend model changes on the branch called `timed-trackables-proposal`. Feel free to reassign

**Comment by lmerriam** [comment]
Thanks @algodave , I'll close for now due to complexity and recreate with updated requirements when we're prepared to work on this one.
