### ISSUE TITLE
Move date and "saved changes" text in check-in

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#110]
Right now it's inconsistent that the date is inside the check-in card on all sections except for the summary where it's outside the card.

I think it would be visually better if the date was always outside the card to show that it is sort of a global.

This should also prevent users from mistakenly thinking that the arrows next to the date are meant to navigate through todays check-in, which we still get sometimes

In addition, we should move the "check-in saved" text to the spot at the top of the card where the date currently is.

<img width="424" alt="screenshot 2016-09-05 01 10 48" src="https://cloud.githubusercontent.com/assets/1657444/18237949/9a317f54-7305-11e6-967e-88e19bb7977b.png">

**Comment by mpugach** [comment]
@lmerriam, deployed to staging

**Comment by lmerriam** [comment]
👍 Looks great, ready to deploy
