### ISSUE TITLE
Link 23andMe accounts

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#112]
To understand whether a symptom is truly influenced by an environmental factor like a treatment or trigger, we need to know whether it is influenced by genetics as well. We believe we can combine our symptom and environmental data with genetic data from a home sequencing service like 23andMe to fund the interaction between genetics and symptoms. Animated explanation here: https://www.youtube.com/watch?v=OKtcW5JpL-w

First we will link users to a landing page:
![fd_genetic_landing_page](https://cloud.githubusercontent.com/assets/1657444/21373682/cad6a43a-c6ee-11e6-88c9-a6c1867812f6.png)
I will work on final copy. The button at the bottom and the link below the video would take the user to 23andMe's authentication page.

Once they have completed authentication on the 23andMe site, they will be redirected back to a success page:
![fd_genetic_success_page](https://cloud.githubusercontent.com/assets/1657444/21373685/cc4d3d9c-c6ee-11e6-835f-0f7cdcf5c7f3.png)

API reference docs here: https://api.23andme.com/docs/reference/
API credentials have been created, will send on request

It appears that we can use [the /genome endpoint](https://api.23andme.com/docs/reference#genomes) to link accounts and automatically request all SNPs, rather than asking users to download their data from 23andMe and subsequently upload it to us. This is a huge improvement because the majority of our users are on mobile and would have trouble moving the files around.

There is an easy version if linking the API is too much work -- we can have the user manually upload their SNPs.

**Comment by mpugach** [comment]
do not see the `/genome` endpoint 

what should trigger a data fetch from the service?

as I understand, we should place it on FD landing page, but I can't find it in the project. Is it another project?

**Comment by lmerriam** [comment]
@mpugach it appears the API has changed. However 23andMe allows users download a `txt` file with all of their data. If we can provide a way for users to upload that file (tagged with their user_id so it can be connected to the user's health data from our CSV data dumps) then our researchers can use it.

If you can get a blank page up that just has an uploader, I can fill it out with the content needed.

**Comment by mpugach** [comment]
should we parse or just store it?

**Comment by lmerriam** [comment]
Only store it

**Comment by mpugach** [comment]
then we need Amazon S3, can you register the account and provide the bucket details in private please?

**Comment by mpugach** [comment]
what is the average size of those files?

**Comment by lmerriam** [comment]
It downloads as a `.zip` around 5.7mb. Unzipped it's 15mb. We could urge them to upload the compressed file.

We won't get many of these, would be lucky to get 10 or 20.
