### ISSUE TITLE
Autosuggest improvements

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#12]
~~1. A new trackable should only become visible in the autosuggest if 5 people independently add it, to make sure that we don't end up with a bunch of variations of the same thing.~~ DONE
1. We should show the number of users like the existing app does:
   <img width="382" alt="screenshot 2016-02-24 14 22 59" src="https://cloud.githubusercontent.com/assets/1657444/13297799/26ffd724-db02-11e5-9264-ff532dcb13c6.png">

**Comment by algodave** [comment]
@lmerriam Can you provide a definition for "number of users" so that I know how to compute it? I looked at the old app's code but I couldn't understand what does that count mean. Thanks

**Comment by lmerriam** [comment]
@algodave that refers to the number of users who have _at some point_ used the trackable. If it's in the history of their check-ins we'd count them.

**Comment by algodave** [comment]
@lmerriam OK I got it. Computation is challenging, I need to think a smart and efficient way to do that ;-)

**Comment by algodave** [comment]
@lmerriam Sorry but I'm puzzling on this: if a user uses a trackable in a lot of checkins, even in non-adjacent periods of time, does that anyways count as 1 right?

**Comment by lmerriam** [comment]
Exactly, it's just the **count of users** who have **tracked that trackable at some point**.

**Comment by algodave** [comment]
@lmerriam Great thanks

**Comment by algodave** [comment]
@lmerriam Puzzling again sorry! When you say _tracked_ do you mean they added it to checkin when it was _today's_ checkin only? Or do you also want to update counts when users go to a checkin in the past and add/remove trackables?

**Comment by lmerriam** [comment]
Yes that should update it as well, if they have it in their history we should count them

**Comment by algodave** [comment]
@lmerriam This is now complete, you can double-check on the live app.
I've run a task on Production env to update all trackable counts per user based on all historic data.

One bonus side-effect we have with the implementation I made is that we keep a count of how many times any given trackable appears in each user's checkins. Perhaps this information might be useful from a data science standpoint as well?
