### ISSUE TITLE
Modal scrolling

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#124]
Modals should be the full width of their content and scroll within the window, instead of having a window that scrolls inside of them.

**Comment by lmerriam** [comment]
Currently modals aren't scrolling at all

**Comment by lmerriam** [comment]
Although the font size decrease works to keep the Profile modal content than the window, it makes it hard to use on touch.

The intent of this ticket was to fix overall modal behavior, so I will keep it open for now.

**Comment by compwron** [comment]
Closing as old for now
