### ISSUE TITLE
Bottom nav bar on mobile

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#127]
On mobile sizes we currently switch to a hamburger menu that makes navigation a chore. Let's use a mobile navbar instead.

<img width="714" alt="screenshot 2016-12-23 00 46 50" src="https://cloud.githubusercontent.com/assets/1657444/21450178/4d155368-c8a9-11e6-953c-69d7194ba7f3.png">

Assets here: https://www.dropbox.com/sh/y1cbfg4hazy0piu/AAAor5dOahdVs8Yxwkpa06Lda?dl=0

Of course, we don't have an "explore" section yet, but it will be added when ready. "Settings" should route to the account modal we already have.

**Comment by mpugach** [comment]
Need mockup

**Comment by lmerriam** [comment]
Mockup added

**Comment by mpugach** [comment]
1.  > "Settings" should route to the account modal

do you mean "edit profile" modal?

2. What about "change password" and "Download data" (CSV)?
3. is history == charts?
4. did you thought how it will stack with future chart navigation bar?

**Comment by lmerriam** [comment]
1) correct, i'm referring to the "edit profile" modal, my mistake
2) Let's put those under the "settings" (we should use that name going forward since we now have more that just profile data there)
3) Yes, we want to start using the name "history" for that section, as I have heard feedback that users understand it's purpose better. That change is user-facing, it's up to you whether we rename the components internally.
4) I will attach a screenshot, it should just stack on top of the nav bar.

**Comment by lmerriam** [comment]
![image](https://cloud.githubusercontent.com/assets/1657444/21487068/d792ab16-cb8e-11e6-89e8-7e12ed356877.png)

**Comment by lmerriam** [comment]
We should also mirror the changes in the desktop navigation, although in reverse order (this is because on mobile most people hold their phone with their thumb on the right side, but on desktop we typically read from the left). So it would be "check-in   history    explore   settings" in the top bar.

I'm curious -- are there downsides to the settings/edit-profile modal being available everywhere? I don't believe it is a UX problem, but if it complicates the routing or requires extra resources to be loaded we could switch to a dedicated template, particularly now that we are adding more to it. Let me know and I can make mocks.

**Comment by mpugach** [comment]
The profile modal logic didn't changed. Same resources are loaded.

2. do you mean to move the form fields or to add a button which navigates to password change modal on profile modal?

**Comment by mpugach** [comment]
how this part should look like, after we remove profile links?

![flaredown 2016-12-27 17-02-36](https://cloud.githubusercontent.com/assets/426179/21502163/98020c76-cc56-11e6-8c17-6836c1294e10.jpg)

should we keep dropdown only to show "logout"? how about mobile?

**Comment by mpugach** [comment]
how about changing the content in same modal?

![flaredown 2016-12-27 17-28-52](https://cloud.githubusercontent.com/assets/426179/21502654/133c6f82-cc5a-11e6-962f-b0e59531f7e8.jpg)

**Comment by lmerriam** [comment]
Good point. I think we should remove that entirely and put everything under the "settings" page. If it's not too much effort to change, it would make sense for this to be a full page so that we can add new sections (like reminders) in the future:

![image](https://cloud.githubusercontent.com/assets/1657444/21514096/db16e21a-cc8e-11e6-9919-3db2f56b91f4.png)

I like your proposal for changing the password within the same card.

**Comment by mpugach** [comment]
is it autosave?
is "change password" a modal?

**Comment by lmerriam** [comment]
Oh sorry I'm moving quick to answer your question and missed some things. Autosave would be nice but we can preserve the same style of having a save button at the bottom of the card if you find it easier.

For "change password" we could change the content of the "account" card, or it could be an independent page. Both work from a UI perspective, so whichever you prefer to build.

**Comment by mpugach** [comment]
how about "change password" be a second card?

**Comment by lmerriam** [comment]
👍 works for me

**Comment by mpugach** [comment]
will fix that tomorrow

![flaredown 2017-01-04 15-49-48](https://cloud.githubusercontent.com/assets/426179/21644356/c3d68d6e-d295-11e6-84f9-db4a4d525639.jpg)

**Comment by mpugach** [comment]
@lmerriam check on staging please

**Comment by lmerriam** [comment]
@mpugach I pushed 2 commits with some style tweaks (forgot to reference issue number)

Only remaining issue is that I get a very large space in between the userengage icon and the navbar or bottom of page. I don't see userengage in my local environment so I can't fix it:
![image](https://cloud.githubusercontent.com/assets/1657444/21704124/f9c58778-d384-11e6-8303-deb6ad6bdbe5.png)

Distance between navbar and userengage icon should be similar to distance between userengage icon and right side of screen.

**Comment by mpugach** [comment]
>  I don't see userengage in my local environment

me neither

but I have an access to deploy staging ))
