### ISSUE TITLE
Wait till user ends typing before querying for search terms

### ISSUE THREAD

**Issue by mpugach** [rubyforgood/Flaredown#132]
User experience a lag between every key press.

So it was proposed to reduce API hits by waiting for user input finish.

@lmerriam [wrote](https://github.com/Flaredown/FlaredownEmber-2/pull/131#issuecomment-265934183):
> That sounds good, as long as the delay is still quick enough to feel responsive to the user. Maybe .2 seconds?

**Comment by lmerriam** [comment]
@mpugach is this issue complete?

**Comment by mpugach** [comment]
yes it is
