### ISSUE TITLE
Upgrade health data security

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#134]
Right now account data (PII) is stored separately from health data (PHI). However, if someone were to break into both DBs they could connect a user's data to their email address via user_id. We should encrypt the user_id so that even if someone was able to obtain copies of both databases, they would not be able to identify users.

Would also like to see a basic proposal for how to store and secure secret keys.

**Comment by mpugach** [comment]
All other secret keys are stored in environment variables on Heroku

**Comment by mpugach** [comment]
@lmerriam `Checkin#user_id` is encrypted on staging, can you please check (old checkins also)?
