### ISSUE TITLE
add Travis CI for free?

### ISSUE THREAD

**Issue by mpugach** [rubyforgood/Flaredown#143]
- [x] Run API tests
- [x] Run API linter (rubocop)
- [x] Run Client tests
- [x] Integrate it with Github to build and show status on every code push

**Comment by lmerriam** [comment]
@mpugach if it will improve your development process, let's do it 👍

**Comment by mpugach** [comment]
It will enforce every developer to fix tests and follow styles

currently there are some JS dead tests (the functional is ok) and Ruby linter complains

**Comment by mpugach** [comment]
@lmerriam could you also check if these options enabled?

![monosnap 2017-01-09 13-38-49](https://cloud.githubusercontent.com/assets/426179/21765362/17442e5a-d671-11e6-83e0-e3899f3d14c2.jpg)

**Comment by lmerriam** [comment]
Should be good to go

<img width="838" alt="screenshot 2017-01-09 10 36 19" src="https://cloud.githubusercontent.com/assets/1657444/21777090/64dfba7c-d66b-11e6-9843-6ba6a12bef48.png">

**Comment by mpugach** [comment]
resolved
