### ISSUE TITLE
Journal view in history

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#155]
Currently it is tough to get to the summary and review past entries like a journal. We should create an alternate "history" view that allows the user to read their data more like a journal.

![image](https://cloud.githubusercontent.com/assets/1657444/21964966/dc455b96-db23-11e6-8acf-aa42e8acac7e.png)

- [x] History can now be switched between Charts and Journal views
- [x] Show list of journal entries starting with the most recent
- [x] Each journal entry shows the average of all symptom severities for the day (0-1 slightly active, 1-2 fairly active, 2-3 very active, 3-4 extremely active)
- [x] Tap "edit" to go to journal entry
- [x] Load 10 or initial entries and auto-load more when the user scrolls near the bottom of the page

**Comment by lmerriam** [comment]
@mpugach this looks fantastic!

Just a few things I did not properly specify:

- [x] Show only days that have journal entries
- [x] Show empty state if the user has no journal entries: "No journal entries yet"
- [x] When caching history, save whether it is showing charts or journal so if I switch to another page I come back to the same view of the history.

**Comment by mpugach** [comment]
@lmerriam see it on staging again

**Comment by lmerriam** [comment]
👍 looks great!
