### ISSUE TITLE
Line graphs should connect across empty days

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#16]
Example: I record a rating for the Abdominal Pain symptom on Wednesday, I don't record one on Thursday, and I do record one on Friday.

Right now the line graph does not draw a line between Wednesday and Friday because Thursday had no value. We should connect the line graph across days, and add dots to show which days were explicitly rated. Quick example:

<img width="726" alt="screenshot 2016-02-24 17 27 08" src="https://cloud.githubusercontent.com/assets/1657444/13303204/e2eee98e-db1b-11e5-85c8-504d7a090c2e.png">

**Comment by lmerriam** [comment]
Looks good! I will have a couple more tweaks, graphs are tricky, but I need to write them down first and make sure I communicate them clearly.

**Comment by safeforge** [comment]
@lmerriam just pushed a couple of fixes, let's close this and open a new one when we're ready with new specs.
