### ISSUE TITLE
Charts scrubber

### ISSUE THREAD

**Issue by mpugach** [rubyforgood/Flaredown#162]
Tap anywhere on the charts to show the scrubber, along with a button displaying the date. Tap on the scrubber again to hide it. Tap the button to navigate to the check-in for that date.

![improved history navigation issue 17 flaredown flaredownember-2 2017-01-20 17-07-18](https://cloud.githubusercontent.com/assets/426179/22154123/f59b070e-df32-11e6-91e7-fb7fb68e5b3c.jpg)

**Comment by lmerriam** [comment]
If this is 16 hrs of work, we may need to come up with an easier design. Will this be easier if the scrubber does not overlap all charts and simply shows a button on the specific chart that was tapped?

**Comment by mpugach** [comment]
I think it will

**Comment by compwron** [comment]
Closing as old for now
