### ISSUE TITLE
show all charts checked in the filter even if there is no data

### ISSUE THREAD

**Issue by mpugach** [rubyforgood/Flaredown#168]

**Comment by lmerriam** [comment]
Max: after playing around with charts we may need to tweak this behavior further. I will clarify today.

**Comment by lmerriam** [comment]
Ok, so I think this is the correct functionality.

1. When user first loads the history, it should default to showing only charts that are present in the currently visible time period.

2. If the user makes a particular chart visible and then navigates to a time when it is not present on their check-in, we should ideally show that the chart is empty with a light grey message that says "No data in this time period" in the middle of that chart. Is this easy to do?

**Comment by lmerriam** [comment]
Do you think it would be helpful to put a button at the bottom of the history that says "show all charts in this time period" when there are hidden charts?

**Comment by mpugach** [comment]
> Do you think it would be helpful to put a button at the bottom of the history that says "show all charts in this time period" when there are hidden charts?

I think the button worth of separate issue

**Comment by mpugach** [comment]
Ok, will implement 1 and 2

**Comment by mpugach** [comment]
but it is not super easy though

**Comment by lmerriam** [comment]
Do you have a general estimate?

**Comment by mpugach** [comment]
end of the monday

edit: but on this monday we have a day off, so next day )

**Comment by lmerriam** [comment]
#2 is less important. If it takes more than a few hrs then we should spend time on more important things first.

**Comment by mpugach** [comment]
deployed to staging but spotted a bug - after adding new treatment, the chart appears, but it is empty until date change

also it is hard to determine the chart color (for blank charts) while there is no trackables data
