### ISSUE TITLE
Improved history navigation

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#17]
Navigating the chart on touch devices is particularly tough, because scrolling up and down to see different trackables conflicts with the left/right dragging gesture to navigate the chart viewport. The goal is to improve navigation patterns.

<img width="660" alt="screenshot 2016-12-22 12 56 05" src="https://cloud.githubusercontent.com/assets/1657444/21440409/bacbf748-c847-11e6-9cf1-d14e1dfdc434.png">

- [x] Navigation buttons that move the chart backwards and forwards in time
- [x] Calendar button that opens a datepicker (mockup uses a screenshot of the PickADate.js plugin). On selecting a date the chart viewport should be centered on that date.
- [ ] ~~Tap anywhere on the charts to show the scrubber, along with a button displaying the date. Tap on the scrubber again to hide it. Tap the button to navigate to the check-in for that date.~~ (extracted to #162)

After some experimenting, it looks like a good date range for mobile portrait is around 10 days. Maybe we can check the user's window width when the page is loaded up and adjust the amount of days in the view such that they are spaced ~32 pixels apart.

**Comment by lmerriam** [comment]
Below is screenshot of the graph navigation on desktop. We may be able to improve the design in the future, but for now easiest is just to use the same navbar with some responsive styles:

![image](https://cloud.githubusercontent.com/assets/1657444/21487571/bde57be8-cb99-11e6-9757-8b35ab6c1f16.png)

**Comment by mpugach** [comment]
how it stacks with bottom navbar https://github.com/Flaredown/FlaredownEmber-2/issues/127#issuecomment-269244516

**Comment by lmerriam** [comment]
![screenshot 2017-01-04 10 55 35](https://cloud.githubusercontent.com/assets/1657444/21648535/55f7d3d0-d26c-11e6-84ba-8cc6fb102599.png)

**Comment by mpugach** [comment]
@lmerriam we need those svgs

![improved history navigation issue 17 flaredown flaredownember-2 2017-01-17 12-59-28](https://cloud.githubusercontent.com/assets/426179/22017924/f54b1ac6-dcb4-11e6-8530-130cdfa63a3a.jpg)

**Comment by lmerriam** [comment]
SVGs: https://www.dropbox.com/sh/gsxogdsxp7v7n5t/AABMAX7K0KCgmsO2iivXxUTma?dl=0

**Comment by mpugach** [comment]
@lmerriam how about to extract the scrubber to a separate issue? I would better return to it after charts filtering and caching

**Comment by lmerriam** [comment]
Sounds good 👍

**Comment by mpugach** [comment]
@lmerriam fixed the userengage position, so check the staging please
