### ISSUE TITLE
Data pull for researchers

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#170]
Can we do a data pull including:
1. All trackables -- weather and food were not included in the last one
2. Obfuscated user_id such that we can post the file in a public repo without compromising security

**Comment by mpugach** [comment]
here it is [export_2017.01.31.csv.gz](https://github.com/Flaredown/FlaredownEmber-2/files/741575/export_2017.01.31.csv.gz)

I reduced the number of SQL requests now it took about 25 minutes (prev export took more than an hour) to export ~40k checkins, although we added foods and weathers.

**Comment by lmerriam** [comment]
Nice work! Closing
