### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#172]
This will probably turn into a more traditional profile eventually, but for now users just need to be able to view their post history, so they can find conversations they have created or participated in.

<img width="707" alt="screenshot 2017-01-30 20 56 34" src="https://cloud.githubusercontent.com/assets/1657444/22449499/9ee51cb6-e72e-11e6-8a7e-0d5e4ae20678.png">

- [x] Show a list of the posts and comments the user has made
- [x] Back button takes user back to the previous page they were on
- [x] Tapping on a post brings the user to that post
- [x] Tapping on a comment brings the user to the post that the comment was made on
- [ ] and scrolls the page to the comment

**Comment by mpugach** [comment]
What user needs to do to navigate to it?

**Comment by mpugach** [comment]
need the bottom navbar icon

**Comment by mpugach** [comment]
@lmerriam what icon should we use for navbar?
