### ISSUE TITLE
New post page

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#173]
Users need to be able to create new posts so they can ask questions, share experiences, and support other users.

<img width="716" alt="screenshot 2017-01-30 22 05 53" src="https://cloud.githubusercontent.com/assets/1657444/22450949/4e4b8f06-e738-11e6-8753-930e969bcc07.png">

- [x] Input for the title of the post
- [x] Input for user's message
- [x] User can select topics via our standard autocomplete input
- [ ] Bonus: add topics automatically based on the content of the title and message
- [x] Cancel button takes the user back to the previous page they were on

**Comment by mpugach** [comment]
~~Are the tags the same with checkin tags?~~
oh it's conditions and treatments, right?

**Comment by mpugach** [comment]
To implement auto topic, we need to implement some AI. It is about NLP. I know some theory (from NN Coursera course) but it's better to engage a colleague of mine. He worked for [Grammarly](http://grammarly.com) in the past.

This should be a separate task

**Comment by lmerriam** [comment]
We will consider the NLP as a future enhancement.

**Comment by lmerriam** [comment]
> Are the tags the same with checkin tags?
oh it's conditions and treatments, right?

Yes! All trackables in fact, unless there are technical limitations.
