### ISSUE TITLE
Post page

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#175]
The post page allows users to view a post, see comments other user have left on the post, leave your own comment, and react to the post and it's comments with emoticons.

<img width="308" alt="screenshot 2017-01-30 22 51 51" src="https://cloud.githubusercontent.com/assets/1657444/22451721/cd42ce72-e73e-11e6-8f8a-1723c926088d.png">

- [x] Show the title and message of the post
- [x] List the comments users have left on the post
- [x] User can enter a new comment
- ~~User can add reaction to the post or comments (I can design an emoji picker if there is not a good existing one. We will use custom emoji for chronic illness)~~ will be implemented in #217

**Comment by mpugach** [comment]
@lmerriam what triggers comment submission?

is this ok?

![flaredown 2017-03-27 17-11-44](https://cloud.githubusercontent.com/assets/426179/24360698/c3123ebc-1310-11e7-9a8f-50abb8cce057.png)

(the green spinner comes from plugin in my browser)

**Comment by lmerriam** [comment]
👍
