### ISSUE TITLE
Mongo performance optimization

### ISSUE THREAD

**Issue by mpugach** [rubyforgood/Flaredown#177]
Hello from mLab,

We are sending this weekly performance report for rs-ds011980 (heroku_vdwtrn6s) because we identified slow operations running on this deployment that could benefit from improved indexing.

In particular, we'd like to call your attention to these:

**collection**
heroku_vdwtrn6s.checkin_treatments
**querycommand**
```{"is_taken": "<val>", "treatment_id": "<val>", "value": {"$options": "<val>", "$regex": "<val>"}}```
**total time:** 
18317 ms
**count:** 
80
**average time:** 
228 ms
**recommended index**
```{"is_taken": 1, "treatment_id": 1, "value": 1}```

**collection**
heroku_vdwtrn6s.checkin_treatments
**querycommand**
```{"is_taken": "<val>", "treatment_id": "<val>", "value": {"$ne": "<val>"}}```
**total time:** 
13439 ms
**count:** 
47
**average time:** 
285 ms
**recommended index**
```{"is_taken": 1, "treatment_id": 1, "value": 1}```

This email contains up to three query patterns selected in order of total time spent by the database, providing our analysis tools support the query pattern and the query occurred more than 20 times. You may have more recommendations waiting on the Slow Queries tab for this deployment (https://mlab.com/clusters/rs-ds011980#slowqueries), including statistics for all observed query patterns.

We provide this analysis because un-indexed and poorly indexed queries consume significant resources and can prevent you from getting the most out of your mLab deployment.

When you create an index, please be aware of these best practices:

Build the index in the background (our management portal does this by default)

Be aware that index creation requires a lot of system resources

Avoid simultaneous index builds by waiting for one to complete before starting another

You can find more guidance on performance and indexing at http://docs.mlab.com/indexing/.

Reply to this email (support@mlab.com) if you have any questions about the performance of these queries, or if anything in this communication is unclear.

Gratefully,
Team@mLab

**Comment by lmerriam** [comment]
The above email was sent by mLab, to view more reports on slow queries you can open mLab from the resources section of the Heroku dashboard.

**Comment by compwron** [comment]
Closing as old for now
