### ISSUE TITLE
Trackable color different from chart to checkin

### ISSUE THREAD

**Issue by algodave** [rubyforgood/Flaredown#18]
@safeforge found a case when trackable color differs from chart to checkin.
Not sure if this is an edge case, @lmerriam might help understanding this.
1. User adds a trackable to a **past day's checkin**; system assigns it a random color and saves it into checkin record. As per req., it won't be tracked on future days, and it won't appear in the chart either.
2. User adds the same trackable to **today's checkin**. As per req., it will be tracked on future days, so system assigns it a random color which gets saved in the tracking record.

Now that trackable appears on chart, but on that past day's checkin from step 1 it continues to appear with its original color, because at that date no tracking record exists for that trackable.

![coding_addiction](https://cloud.githubusercontent.com/assets/2955556/13361836/5bb851b0-dcc1-11e5-8081-8bbc214cf03c.png)

![screen shot 2016-02-26 at 19 24 03](https://cloud.githubusercontent.com/assets/2955556/13361838/5ff0d0ea-dcc1-11e5-98ff-49933296435a.png)

**Comment by lmerriam** [comment]
Ideally the color for a trackable would be decided whenever the first creates the trackable and stay the same for past, present and future days

**Comment by algodave** [comment]
This is now obsolete and can be closed
