### ISSUE TITLE
Updated chart hide/show controls

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#188]
The modal window is a poor way to hide/show tags and food.

<img width="398" alt="screenshot 2017-02-08 23 25 52" src="https://cloud.githubusercontent.com/assets/1657444/22769407/56b3fc94-ee56-11e6-86ea-ceb665c27217.png">

- [x] "Hide" buttons above charts
- [x] "Add a chart" searches through all the user's trackables, on selecting it should be made visible

**Comment by mpugach** [comment]
> on selecting it should be made visible

and disappear from dropdown suggestions, right?

**Comment by lmerriam** [comment]
Yes! Or it can be greyed-out. Whichever is easier.

**Comment by mpugach** [comment]
@lmerriam check please

**Comment by lmerriam** [comment]
Works well! Let's add tags next
