### ISSUE TITLE
Auto logout triggered by accessing non global trackables owned by other user

### ISSUE THREAD

**Issue by mpugach** [rubyforgood/Flaredown#190]
Found a strange behaviour while was playing with #155 on staging.

One checkin had a treatment with `global: false` attribute and relation to other user in `UserTreatment` table.

The authorization currently configured to deny access to such treatments.
The frontend authorization library logs me out avery time it receives 401 from backend.

It means I cant access journals and treatment page of that checkin.

I do not remember how "Placebo" by Thomas appeared there in my checkin.

To fix this I need someone to explain the story behind the `global` attribute and user relation to treatment.

@algodave @lmerriam can you please? how it  should behave?

**Comment by lmerriam** [comment]
I am unaware of the purpose of the `global` attribute. @algodave @safeforge do you know what it is used for?

**Comment by lmerriam** [comment]
Closing, this is part of another issue now
