### ISSUE TITLE
decrease data processed on client and backend to show charts

### ISSUE THREAD

**Issue by mpugach** [rubyforgood/Flaredown#198]
Currently no matter what charts are visible all data is fetched anyway.

In the future it may come a performance issue.

**Comment by lmerriam** [comment]
Excellent point, we should absolutely do this, it is already a problem for some users who say the history freezes or takes too long to load (some people have over a hundred trackables)

**Comment by mpugach** [comment]
The main point of the issue is to decrease the data is being serialized on backend, passed through network, desirialized on client and participated in computations.

After closer look I thought it may be easier to implement some filters query params with same API requests.

Will pick what suits better.

**Comment by mpugach** [comment]
@lmerriam check on staging please

**Comment by lmerriam** [comment]
The charts seem to work great! Of course I can't test performance on the backend but it sounds like this reduces API calls significantly?

#200 is a separate issue, correct?

**Comment by mpugach** [comment]
It reduces a huge payload of one API call (charts), for a user with many trackings and only few charts
also it saves charts computation on client in his case, since there is less data to process

it saves several double calls and removes one call completely (profile now is included into user) 

on backend it also vary from scoped DB requests to no requests at all
and it serializes less data into JSON

the performance of backend is not ideal in general:
- since we have two DBs, the joins takes several requests instead of one
- `globalize` gem does not simplifies the life, it stores localization in a separate table (may be we should look at [hstore_translate](https://github.com/Leadformance/hstore_translate) or skip the localization)

both of these generates a lot of N+1 queries

it's a normal way to develop such applications:
1. build something
2. adopt to changed requirements
3. do performance optimization (code quirks, caching, API and frontend restructuration, big rewrites if technical debt is too big) or buy more servers if it helps

I'm not different from many developers that also find less obvious [fatal flows](http://www.drdobbs.com/windows/a-brief-history-of-windows-programming-r/225701475) :)
In most cases it is result of step 2 from above.
But it is hard for me to answer the question "[can we live without it?](http://kmstandards.com/wpblog/wp-content/uploads/2014/10/projectManagementTriangle-e1412797550456.png)", there are different life periods of the project.

#200 is a separate issue

**Comment by lmerriam** [comment]
I am all for optimization when needed! Both for performance and because I don't want you to burn out on a codebase that is hard to work with. Let me know when you see something that you judge to be in need of optimization and we'll figure out if/when to do it.

> since we have two DBs, the joins takes several requests instead of one

Unfortunately this will likely be a permanent requirement so that we can store identifiable data separately from health data.
