### ISSUE TITLE
Set user’s most-recently used treatment doses as default when it's "turned-on"

### ISSUE THREAD

**Issue by algodave** [rubyforgood/Flaredown#2]
The most recent dose used for a treatment has to be saved for each user, in order to allow him to quickly select it during checkin

**Comment by algodave** [comment]
Summary of slack conversation with @lmerriam to clarify reqs
- as soon as the user "turns on" a treatment, it automatically gets its last dose, if it has one
- it would look at the last day the user logged prior to the day they are checking in and use that dose
- this can be done whatever the checkin day is, so no reason to differentiate behavior between today's checkin and past days

**Comment by lmerriam** [comment]
:+1:

**Comment by lmerriam** [comment]
@algodave this isn't quite working for me, I still get "no dose" on all my treatments when I add them

**Comment by algodave** [comment]
@lmerriam can you provide an example treatment you added which was not populated? Consider that currently you have to wait one second before "turning-on" the treatment just added in order to see the auto-set dose (sorry I should have mentioned that) 
I'll fix this together with #3 which will provide the app with better awareness on when to trigger checkin save.

**Comment by lmerriam** [comment]
Prednisone, Stelara, Folic Acid, Methotrexate on my logan@flaredown.com account

Just tried again waiting 10 seconds, I still see the issue unfortunately

**Comment by algodave** [comment]
@lmerriam I should have found what the issue was. I was discarding `null` doses but not blank ones. Please try again when you have a chance and let me know. Also note: on a new checkin default doses are immediately available; when you add a new treatment instead, you have to wait one second.

**Comment by lmerriam** [comment]
Looks good now :+1:

**Comment by lmerriam** [comment]
@algodave still seeing issues: https://www.dropbox.com/s/zjz5t0f651auuas/autoTreatmentDose.mov?dl=0

**Comment by algodave** [comment]
@lmerriam just watched the video. The checkin you clicked on already existed before I released the feature, that means the object was initialized without most-recent doses. I realized that because the summary screen opened up rather than the first checkin screen (the "You haven't checked-in yet"). 
So to recap: the feature works on new checkins you create from now on, and on not-yet initialized past checkins (i.e. the ones for days which you've _never_ clicked on, if any)

**Comment by algodave** [comment]
@lmerriam oh by the way, if you want to test on some past day, I can manually remove your existing checkins; just give me the dates in case you want to do that

**Comment by lmerriam** [comment]
Gotcha! Makes sense. If you wanna clear the past 5 days of my check-ins that would be awesome

**Comment by algodave** [comment]
@lmerriam Done!

**Comment by lmerriam** [comment]
@algodave getting the same thing i got before, it seems to be targeting the wrong dose. right now i added a "5mg" dose of prednisone in the days you recently cleared for me, then the next day I turned on prednisone and the auto-dose was "3mg". I have used 3mg before, but not the prior day. Any way I can help diagnose?

**Comment by lmerriam** [comment]
video, in case I'm doing something weird again: https://www.dropbox.com/s/0wzv58dlcdj0p4c/autoTreatmentDose2.mov?dl=0

**Comment by algodave** [comment]
No, this time you're not doing anything weird :)
Let me better investigate tomorrow, I'm reopening.

**Comment by lmerriam** [comment]
Random UX thought: if the last dose was "no dose" the auto dose should be "no dose"

**Comment by algodave** [comment]
Oh this is important, thanks for posting! At the moment it's ignoring both `null` and `blank` values while retrieving the most recent. I'll change that.

**Comment by algodave** [comment]
@lmerriam You can now test again; let me know which days should I delete checkin for you, if needed.

**Comment by lmerriam** [comment]
Works for me! Closing :+1:
