### ISSUE TITLE
Scroll to top when routing

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#201]
When the app routes it preserves scroll position. This means that when navigating between pages the user is often dropped into the middle of the next page.

This is the ideal scroll-to-top behavior, because it still preserves scroll position when using browser history: https://github.com/dollarshaveclub/ember-router-scroll

**Comment by mpugach** [comment]
see on stage

**Comment by lmerriam** [comment]
Working for me!
