### ISSUE TITLE
upgrade to Rails 5.1 when it is released (currently beta)

### ISSUE THREAD

**Issue by mpugach** [rubyforgood/Flaredown#207]
depends on #206

> As per our maintenance policy, the release of Rails 5.1 will mean that bug fixes will only apply to 5.1.x, regular security issues to 5.1.x and 5.0.x, and severe security issues to 5.1.x, 5.0.x, and 4.2.x. This means 4.x and below will essentially be unsupported!

**Comment by compwron** [comment]
Done!

**Comment by benlangfeld** [comment]
We're still using Rails 5.0, but a 5.1 upgrade is planned in https://github.com/rubyforgood/Flaredown/issues/473, indeed all the way to 6.1.
