### ISSUE TITLE
Integrate intercom

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#21]
Send the same information as the existing app:
- [ ] Demographic and profile data
- [ ] Check-in event
- [ ] Onboarded event

Create a new "app" on intercom so stats are kept separate from the old app.

**Comment by algodave** [comment]
@lmerriam I've found Intercom-related code on the old app but it seems to me that only the first item is covered, because I only found code that creates users with the following info:
- email
- country
- sex
- birth date
- signup date
- onboarded (true/false)

I'm not finding any code which would send events to Intercom. Of course it's not an issue to implement that, but I want to be sure that's what you're expecting.
It would be useful if you posted some screenshots of what you currently get on your intercom dashboard for the old app.

**Comment by lmerriam** [comment]
You're right! The events are set up in intercom's dashboard. The data you listed should cover it 

On Sun, May 15, 2016 at 9:50 AM -0700, "Davide Papagni" notifications@github.com wrote:

@lmerriam I've found Intercom-related code on the old app but it seems to me that only the first item is covered, because I only found code that creates users with the following info:

email
country
sex
birth date
signup date
onboarded (true/false)

I'm not finding any code which would send events to Intercom. Of course it's not an issue to implement that, but I want to be sure that's what you're expecting.

It would be useful if you posted some screenshots of what you currently get on your intercom dashboard for the old app.

**Comment by algodave** [comment]
@lmerriam Thanks. Another question: did the Intercom Messenger appear on some specific page of the old app?

**Comment by lmerriam** [comment]
No it was app-wide

On Sun, May 15, 2016 at 10:09 AM -0700, "Davide Papagni" notifications@github.com wrote:

@lmerriam Thanks. Another question: did the Intercom Messenger appear on some specific page of the old app?

**Comment by algodave** [comment]
I'm going to attach the following custom attributes to intercom users:

![intercom_user_custom_attributes_new](https://cloud.githubusercontent.com/assets/2955556/15295010/db7f4eec-1b8e-11e6-88eb-f9b411db379f.png)

**Comment by lmerriam** [comment]
Sounds good, these are probably the most important. The only one that's
missing, which I currently use the most, is the number of check-ins the user
has created (with any amount of data).

**Comment by lmerriam** [comment]
Nevermind! Turns out we don't have that. I've been using "web sessions" as a
proxy. If it's super easy to do it would be helpful though.

**Comment by algodave** [comment]
@lmerriam Returning the checkins count per user is super-easy from a coding standpoint, but I have the strong feeling that it's currently inefficient and would slow-down the app (we would need to adjust the model with some counter caches).
However to this purpose, I suggest we tackle that in a better way by leveraging Intercom Events.
We could have the backend fire events for those actions that you find relevant - the [intercom-ruby](https://github.com/intercom/intercom-ruby) gem comes to the rescue ;-)
So I would say: let's just have users with custom attributes as a 1st pass, then you could take your time to think of a complete list of events you would like to be tracked on Intercom, and then you would open a new issue which we'll tackle in the next milestone.
What do you think?

**Comment by lmerriam** [comment]
Perfect, sounds good to me

**Comment by algodave** [comment]
@lmerriam I have created a new Intercom app as per your suggestion (called it Flaredown2, what a poor fantasy!)
Now you need to turn on desired features for the Intercom Messenger:

![screen shot 2016-05-16 at 18 54 55](https://cloud.githubusercontent.com/assets/2955556/15296911/e2a224e8-1b97-11e6-84e1-29bdd4a368f1.png)

**Comment by lmerriam** [comment]
@algodave I think the new app is under your account, I don't see it in mine. I can create one and invite you if that's easiest. I've got the subscription for messenger already.

**Comment by algodave** [comment]
@lmerriam I think that's better if you create the new app and invite me ;-) 
Thanks

**Comment by algodave** [comment]
I had to add additional code in order to support Secure Mode as it was enabled by the old app, and once enabled it can't be disabled. So far so good, we're more secure ;-)
