### ISSUE TITLE
Users unable to load charts

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#215]
Charts "loading forever" last few days. It seems to be per account, as users who have this problem report it on both their phone and their computer. Maybe related to recent chart optimization work?

@mpugach I will send emails of affected user accounts to you privately for inspection.

**Comment by lmerriam** [comment]
Screenshot from one user: 
![image](https://cloud.githubusercontent.com/assets/1657444/23836047/0f570f02-0748-11e7-8914-09b4374dfaf2.png)

**Comment by mpugach** [comment]
need to verify it is fixed (for me it is)

**Comment by lmerriam** [comment]
@mpugach I will ask the users who reported it to check

**Comment by lmerriam** [comment]
According to one user who reported, it is fixed. I am closing for now unless one of the others responds to the contrary.
