### ISSUE TITLE
Try out product analytics platforms

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#216]
I would like to trial a few analytics platforms and pick the one that works best for Flaredown. If it won't cause performance trouble, I'd like to try them out at the same time. Otherwise we could swap them out one by one.

The services I'm interested in are:
Heap
Mixpanel
Amplitude

I have created accounts and will forward install info.

**Comment by mpugach** [comment]
Heap is deployed

Is API key == Secret key for Amplitude?
![projects - amplitude 2017-03-13 17-28-15](https://cloud.githubusercontent.com/assets/426179/23861376/859e6d52-0812-11e7-887f-3fc3d27fa470.jpg)

Got invitation to Mixpanel but do not see the project

**Comment by mpugach** [comment]
Amplitude is on prod, but we need to track something

**Comment by mpugach** [comment]
@lmerriam check the amplitude events on production

**Comment by lmerriam** [comment]
@mpugach I see them! When adding/removing trackables can we set the Type and Name as `properties`? I believe Amplitude allows that but let me know if not. The issue is that right now every new trackable added is a brand new event because they are uniquely named. Ideally they should be just "Add trackable" or "Remove trackable" events with properties.

**Comment by lmerriam** [comment]
Can we easily send the same events to mixpanel and heap?

**Comment by mpugach** [comment]
adjusted and deployed Amplitude

need to dive into Heap and Mixpanel docs for that, will do it tomorrow

**Comment by mpugach** [comment]
Heap tracks all automagically, see the video to configure events without any code https://vimeo.com/116133473

**Comment by mpugach** [comment]
Same with mixpanel, can be configured with their GUI

**Comment by lmerriam** [comment]
@mpugach we can remove all but Heap

**Comment by mpugach** [comment]
done
