### ISSUE TITLE
Emojis in journal

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#217]
Emoji are a great way for people to express themselves with text. We're illustrating a set of custom chronic illness emoji for the upcoming discussion, and I would like to give users the ability to add them to their journal entries as well.

I am open to suggestions for UI as there may be a good solution out there already so that we don't have to build a custom one. Of course, it needs to be mobile friendly.

I found this after a quick search, in case it's helpful: https://github.com/Deveo/ember-emojione

- [ ] User can open emoji picker on mobile and desktop
- [ ] Uses our custom emoji

**Comment by mpugach** [comment]
EmojiOne is the best and only one emoji picker did not found anything better so far. But it is not customizable.

![emojione frequently asked questions 2017-04-10 17-30-46](https://cloud.githubusercontent.com/assets/426179/24866673/88dd3374-1e13-11e7-8f31-26953a42fbc4.png)

**Comment by lmerriam** [comment]
@mpugach we definitely need to be able to use our custom emoji. Even if the other options aren't as good, is there one that would allow custom emoji that we could start with?

This script is recently updated and it looks like we could swap out the sprite sheet to customize the images: https://github.com/OneSignal/emoji-picker

**Comment by mpugach** [comment]
it not about sprite sheet only, it is about definitions and mapping also

`emoji-picker` converts everything into a text editor, so is not suitable for discussion's "add reaction" feature. Also, it lacks text replacement/completion while typing.

this looks more customizable https://github.com/frissdiegurke/emoji-parser, but there is no picker

still looking...

BTW, about "add reaction" should there be a counter?

**Comment by mpugach** [comment]
on another hand, we can try to fork and modify `emoji-picker` to include custom images and call the picker without an editor field

this will not fix selection by typing though

**Comment by lmerriam** [comment]
Old but maybe useful? https://github.com/diy/jquery-emojiarea

**Comment by lmerriam** [comment]
It's OK if they can't enter emoji by typing, I think most people will use whatever picker we make anyway.

**Comment by mpugach** [comment]
@lmerriam see this on staging

I'm not sure we should force users to navigate to the post in order to leave the reaction...

**Comment by lmerriam** [comment]
I think you're right, when I'm on the discussion page I keep trying to click the reactions.

This looks great Max! Me and susie had a lot of fun with it on staging.

**Comment by compwron** [comment]
seems done
