### ISSUE TITLE
Import users accounts from existing app

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#22]

**Comment by algodave** [comment]
@lmerriam Do we need to import checkin data too?

**Comment by lmerriam** [comment]
@algodave I would like to, so existing users don't lose 6 months of data. But if it's going to be a really tough thing to do, we might be able to get around it

**Comment by algodave** [comment]
Will take a closer look in the very next days and get back to you.

**Comment by algodave** [comment]
@lmerriam Good news! We can import checkin data as well as users data, it's an 8 to 10 hrs job.

**Comment by algodave** [comment]
@lmerriam Better news! I completed a first draft of the export task, here's what I'm able to get (of course, from my own local env app instance):

https://gist.github.com/algodave/5e5bd33fbbd1976f8d5e

**Comment by lmerriam** [comment]
This is great @algodave !
