### ISSUE TITLE
"United States" higher on list of countries during signup

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#231]
70% of our users are from the US but they have to scroll all the way to the bottom of the dropdown during signup to select the country. We should move our top countries to the top or allow the user to type.

**Comment by lmerriam** [comment]
@mpugach I can't figure out where the list of countries is coming from

**Comment by mpugach** [comment]
I can. Will look closer on Monday

**Comment by lmerriam** [comment]
Ok, I believe we would mainly want to put the US and UK at the top.
