### ISSUE TITLE
Weekly digest email

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#233]
Currently we're doing a good job of helping people track and store information, but we aren't doing a great job of giving them feedback on that data. A weekly digest will help remind people to track, as well as give them useful aggregate info about the past week.

If the user checked-in in the past week:
![fd_weekly_digest](https://cloud.githubusercontent.com/assets/1657444/24334853/683f65ee-1240-11e7-9102-47c520661d20.png)

If the user did not check in in the past week:
![fd_weekly_digest_empty](https://cloud.githubusercontent.com/assets/1657444/24334856/7163ff72-1240-11e7-8efc-2c91eb0a8931.png)

- [ ] Highlight best and worst days based on their average symptom+condition activity in past week
- [ ] Display the average weekly activity vs the average previous week
- [ ] Display the symptoms and conditions with the most change relative to the previous week. We should set a minimum amount of difference (10%) and a maximum number of trackables to show so the email isn't too long (5 improved, 5 worsened)
- [ ] Option to turn on/off in settings
- [ ] Option to turn on/off in final step of onboarding
- [ ] Unsubscribe link in email
- [ ] Show empty state email if no check-in in past week

Question: what should we do if no data from previous week?

**Comment by compwron** [comment]
Closing as old for now
