### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#241]
It's impossible to carry on a conversation if you don't know that someone has replied. We should notify the user when someone has replied to a topic they posted in the app and externally as well.

<img width="773" alt="screenshot 2017-04-09 22 37 41" src="https://cloud.githubusercontent.com/assets/1657444/24843936/28437be8-1d75-11e7-918d-06fa0b097f10.png">

I should get notifications for:
- Comments on my post
- Reactions to my post or comment, see #217 
- Mentions from another user, see #243

---
- [x] Change the discussion icon if there are new replies
- [x] Display counter of unread notifications in notification icon
- [x] Optional: Notifications of the same type and on the same message (for instance, replies on the same topic) should be grouped if possible. Similar to facebook.
- [x] Tapping a notification should take you to that post or comment
- [x] User should get an email notification of a new message and a link to open it. If possible we should wait and group notifications before sending so we don't flood a user's inbox for popular posts.
- [x] Rename "my posts" section to "my activity" and include notifications (see note below)
- [x] Routing: if user has unread messages the discuss link in the navbar should take them to notifications, otherwise it should take them to the discussion landing page
- [ ] When the user visits the notifications, they should see a separator to indicate which notifications are new
- [x] Once the user visits the notifications, they should all be marked as READ and the notification counter should disappear

The way I have designed this screen combines "my posts" and the notifications into one "my activity" page. If this is tough to do then let me know, we can split them into separate pages and I can figure out where to put a button to get to notifications.

**Comment by mpugach** [comment]
how long should we wait to group emails?

**Comment by lmerriam** [comment]
Maybe 30 min. As I think about it though, let's save that requirement for later and implement it only as-needed.

**Comment by lmerriam** [comment]
Per our discussion earlier, let's move notifications to their own section:

<img width="327" alt="screenshot 2017-05-04 01 16 24" src="https://cloud.githubusercontent.com/assets/1657444/25691288/4f048204-3067-11e7-841e-8db687591525.png">

**Comment by lmerriam** [comment]
@mpugach I see the deploy! However when I try to test it out I'm not seeing notification emails yet.

Was looking at the email template and it reminded me that one thing we'll need is an option to turn the emails on/off in the user settings, and then we give them an unsubscribe link that just sends them to their settings.

**Comment by mpugach** [comment]
the heroku scheduler has only three options: 10m, 1h, 24h. Currently, it is set to 1h.

You are right, we should implement the unsubscribe and settings option

**Comment by lmerriam** [comment]
Gotcha! 1hr is good

**Comment by lmerriam** [comment]
@mpugach is this easier if we don't have the separator and just highlight all unread notifications?

**Comment by mpugach** [comment]
@X-tina check please ^^^

**Comment by lmerriam** [comment]
Working well!
