### ISSUE TITLE
Updated navbar icons

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#242]
Here is a link: https://www.dropbox.com/sh/qmfbw7ovovgtqa3/AACNqraj87pgCpa1ot459lyKa?dl=0

The SVGs seem to be exporting strangely, but I'm not sure if that's just the mac viewer as the Figma app sees them fine. Let me know if they work, I've included PNGs as a backup.

**Comment by mpugach** [comment]
previous were the same, I asked my colleague to fix them with Adobe Illustrator

downloading the trial now
