### ISSUE TITLE
Unified navigation in Discussion

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#258]
To improve ease of navigation in the discussion, it would help to have a navbar that is consistent across pages. 

<img width="732" alt="screenshot 2017-05-04 01 44 17" src="https://cloud.githubusercontent.com/assets/1657444/25691721/92f83e02-306b-11e7-9d11-00ede1f8c5bb.png">

<img width="755" alt="screenshot 2017-05-04 00 59 25" src="https://cloud.githubusercontent.com/assets/1657444/25691018/f910c18e-3064-11e7-82ee-dff4c5894093.png">

- [x] Sticky behavior: hide when scrolling down and reveal when scrolling up
- [x] Show back button
- [x] Show title of current page
- [x] Search icon opens up a textbox with the search
- [x] Profile icon opens up current user's profile
- [x] Mail icon opens up notifications
- [x] Mail icon shows an alert when there are unread notifications

SVG icons here: https://www.dropbox.com/sh/d2qq2b4akooc5f4/AAAA4Q_vWy_ZUuE3FZkyJNXHa?dl=0

**Comment by mpugach** [comment]
@lmerriam it seems like the title of current page is the destination of the arrow

maybe if place it in a center...

**Comment by lmerriam** [comment]
<img width="512" alt="screenshot 2017-05-11 08 30 15" src="https://cloud.githubusercontent.com/assets/1657444/25949029/15b68fde-3624-11e7-908b-1423a5b323a5.png">

**Comment by mpugach** [comment]
@lmerriam the envelope alerts about unread notifications now, should we remove the logic and counter from the bottom discussions link?

**Comment by mpugach** [comment]
can you provide SVGs please? we could utilize http://www.flaticon.com/ but their free license requires mentioning and link to their site somewhere in the app

http://support.flaticon.com/hc/en-us/articles/207248209-How-I-must-insert-the-attribution-

**Comment by mpugach** [comment]
missed your dropbox link )

**Comment by lmerriam** [comment]
Let's keep the behavior of the bottom discussions link -- it's the more important one because it notifies users when they are in other parts of the app. I don't think it's too bad to have both notifying the user, even if it is a little bit redundant.

**Comment by lmerriam** [comment]
@mpugach I should have been more explicit with the mockups! The "x" was intended to close the search box, not to clear it. As well, I just realized that we don't need the "go" button because we are selecting topics from a dropdown. I was working too fast and missed a lot here

I believe it can be reformatted like this:
<img width="655" alt="screenshot 2017-05-24 00 51 31" src="https://cloud.githubusercontent.com/assets/1657444/26387410/78216bde-401b-11e7-9f6e-65c628611bcb.png">
- [x] X closes the searchbar
- [x] Selecting a topic navigates to the topic page, remove the "go" button

**Comment by lmerriam** [comment]
One more update -- let's show the type of trackable and user count in the dropdown:
<img width="572" alt="screenshot 2017-05-24 01 33 08" src="https://cloud.githubusercontent.com/assets/1657444/26388222/0fa7c0e8-4021-11e7-81ab-9921cc41e3c2.png">

**Comment by lmerriam** [comment]
Looks good!
