### ISSUE TITLE
Back button functionality

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#262]
There are two common use cases in which the back button does not work:
1. If the user follows a link from outside of Flaredown
2. If the app reloads a page with the back button--this happens commonly when the mobile app is running in the background for a while and gets removed from memory, and then the user opens it again -- it will open the page the user left it on and if there is a back button it will not work.

For number 1 we should default to sending the user back to the top-level discussion. For number 2 ideally we'd be able to keep track of the last page across the reload? But I don't know if it's possible to distinguish between the two cases.

**Comment by mpugach** [comment]
I do not see a way to distinguish between those two. Let's follow scenario 1

**Comment by lmerriam** [comment]
👍
