### ISSUE TITLE
Hide back arrow when there is no history

### ISSUE THREAD

**Issue by refractslight** [rubyforgood/Flaredown#269]
Back arrow doesn't seem to do anything.

<img width="35" alt="back" src="https://cloud.githubusercontent.com/assets/20187086/26227128/086bd6a4-3bf6-11e7-99ff-b15cc5db798a.png">

Tested on:
Chrome 57.0.2987.133
Mac OS Sierra

and

Chrome 58.0.3029.83
Nexus 5 Android 6.0.1

Navigated to several different pages. 'Back' takes me to the previous page, but once there, the arrow does nothing.

**Comment by lmerriam** [comment]
I think the issue is that the back button the discussion page has no history to navigate to at this point, so it navigates to /posts. What do you think about changing that logic so the back button doesn't display in that case?

**Comment by lmerriam** [comment]
Currently when there is no history the back button routes to `/posts`. We should change that so that it does not show at all if there is nothing to return to.

**Comment by lmerriam** [comment]
Works for me!
