### ISSUE TITLE
Weekly "top posts" email

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#289]
To bring users into our discussion regularly, we should email them some of the most popular posts in topics they follow once per week.

![weekly top posts email](https://user-images.githubusercontent.com/1657444/27263771-76d20f9a-543e-11e7-843e-b2e3bf9ed2eb.png)

- [x] Show top five posts (calculated by number of reactions+comments) in topics that the user is following over the past 7 days
- [x] If we run out of posts from topics the user is following, pull from ALL posts
- [x] Send on Tuesday morning at 10am (either localized to the user, or use EST if it's simpler)
- [x] Add an option in the settings to turn off this email
- [x] Unsubscribe link at the bottom of the email
- [x] Remove from onboarding step

**Comment by compwron** [comment]
Closing as old for now
