### ISSUE TITLE
Navigating to some topics logs the user out

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#299]
It appears to be topics that are newly-created or have only one follower? Here are a couple of examples:

Click `amplified musculoskeletal pain syndrome` on this post: https://app.flaredown.com/posts/59558a8dc361c30004513e69

Click `Osteogenesis Imperfecta` on this post: https://app.flaredown.com/posts/59546ac2bf7f6000042b498e

**Comment by X-tina** [comment]
@lmerriam 
Such behavior occurs because of 'global' flag of Topics.
If an author of Local Topic created a Post, it becomes visible on the Discussion page.  Another user becomes unauthorize after trying to access to this local Topic.

**Comment by lmerriam** [comment]
Fixed 👍
