### ISSUE TITLE
Routing to onboarding not working

### ISSUE THREAD

**Issue by algodave** [rubyforgood/Flaredown#30]
There seems to be an issue when including more than 2 `beforeModel` hooks in the same route.
After implementing `beforeModel` hook in [index route](https://github.com/Flaredown/FlaredownEmber-2/blob/master/frontend/app/routes/index.js#L13), the same hook in [OnboardedRoute mixin](https://github.com/Flaredown/FlaredownEmber-2/blob/master/frontend/app/mixins/onboarded-route.js#L5) stopped getting called for some reason.

**Comment by algodave** [comment]
However, `OnboardedRoute` mixin is currently imported by `index` route only!
I'm also thinking that in general, both the new default route logic (as per #27) and the pre-existing "route to onboarding" logic, should anyways stay in the same place, which is the route configured as `routeAfterAuthentication` (currently `/` - i.e. `index`).
So, I'm going to merge the 2 `beforeModel` hook impls into one, keep it into `index` route and kill `OnboardedRoute` mixin. In case `routeAfterAuthentication` changes to another route later, the `beforeModel` hook impl would be moved to the new route.

**Comment by lmerriam** [comment]
sounds great :+1:
