### ISSUE TITLE
Deleting posts and comments

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#308]
When users make a mistake, they want to be able to remove their comment, but currently they can't.

<img width="722" alt="screenshot 2017-07-08 18 02 28" src="https://user-images.githubusercontent.com/1657444/27989489-b87d5638-6407-11e7-9b06-6b0160d6712f.png">

- [ ] Dropdown icon in the top right of posts and comments (similar to facebook)
- [ ] Visible only to the user who posted
- [ ] Confirmation popup if the user taps delete: "Are you sure? This cannot be undone. [Delete] [Cancel]"

**Comment by compwron** [comment]
Closing as old for now
