### ISSUE TITLE
Parse URLS in posts and comments and turn them into links

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#311]
Users often want to link other users to content. When a URL is entered into a post or comment, it should be turned into a link so other users can follow it.

- [ ] Open the URLs in a new window (`target=_blank`) so that the in-app users do not get stuck on an external page

- [ ] ONLY IF EASY TO DO: if the URL is an `app.flaredown.com` url, simply navigate to it and do not open it in a new window

**Comment by compwron** [comment]
Closing as old for now
