### ISSUE TITLE
Local trackables visible in discussion and checkin?

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#313]
@X-tina for reference: user-created trackables on Flaredown are supposed to start `local` and become `global` once 3 users have independently added them. This ensures that users can add anything they want to track without suggesting it to everyone. However if multiple people add a trackable, we can make it global and include it in suggestions.

We should check that the functionality described above, because some of the trackables that are visible in the autocomplete do not seem like they could have been added independently by multiple people:
<img width="561" alt="screenshot 2017-07-08 18 58 04" src="https://user-images.githubusercontent.com/1657444/27990752-4602087e-642f-11e7-8eb2-43e72a4f474d.png">

**Comment by X-tina** [comment]
@lmerriam, issue was deployed to staging.

**Comment by lmerriam** [comment]
I have been testing this on production -- I created a brand new tag called "globaltest" in my checkin then switched to another account and I was immediately able to find it in the tag search and discussion. 

To make sure I am explaining it correctly, here is a diagram of the intended functionality:
<img width="1073" alt="screenshot 2017-07-30 19 56 13" src="https://user-images.githubusercontent.com/1657444/28760691-c9ce218a-7576-11e7-98d1-6c2cacfd2a60.png">
This is the _only_ functional difference between them.

**Comment by X-tina** [comment]
- [x] Local visibility for tags and foods
- [x] New tests for user abilities
- [x] Hide local health factors from recent and popular query
- [x] Fix travis tests
- [x] Add test for Food fts query 
- [ ] Add auto following for tags while checkn

**Comment by X-tina** [comment]
@lmerriam 
Deployed on production.
Do we need to follow local tags after tracking them? (Like conditions, symptoms...)

**Comment by lmerriam** [comment]
@X-tina oh, interesting! No, that should be manual.

**Comment by lmerriam** [comment]
Nice, it's working!
