### ISSUE TITLE
Performance monitoring

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#318]
To improve performance, we need to understand where the bottlenecks are. Here are a couple of performance monitoring options that I see:

On the rails side, skylight.io provides a nice free tier that will accommodate our app. I created account and put in a pull request, the instructions to deploy are here: https://www.skylight.io/support/advanced-setup#deployment

On the client side, is there a good solution? New relic is available through Heroku, though I hear they are not great for ember apps and I am not seeing a lot of other options.

@X-tina would like to hear your opinion -- should we use a performance monitoring platform? If so do you have a preference?

**Comment by compwron** [comment]
Currently using Heap
