### ISSUE TITLE
Progressive web application capabilities

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#321]
Because we serve our web app primarily to mobile devices through browsers we can benefit greatly from progressive web app features. A good resource to follow for ember is: https://madhatted.com/2017/6/16/building-a-progressive-web-app-with-ember

The important points:
- [ ] Manifest file
- [ ] Register service worker (bonus: fall back to appcache on non-supported browsers)
- [ ] Offline sync - respond with 200 when offline and the app continues to function

**Comment by mpugach** [comment]
the biggest challenge here is offline sync other steps are simple.

For example, we have ~15000 Food items, just to fetch them all page after page will dramatically affect the performance. What if one of them is changed?

Another case, the user changes same data from two offline devices, how to resolve the conflict?

**Comment by lmerriam** [comment]
Thanks for the explanation @mpugach ! Closing this issue for now
