### ISSUE TITLE
Error: "The adapter rejected the commit because it was invalid"

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#322]
This error is cropping up a lot recently and it seems to be a breaking error.

https://flaredown-errors.herokuapp.com/apps/5967bb275b8b3b00090001fb/problems/596805985b8b3b0007000251

**Comment by lmerriam** [comment]
Is this tied to fastboot or can we deploy it separately?

**Comment by X-tina** [comment]
@lmerriam 
I'm not sure, can't reproduce it. I'm going to add extra data to error reports in order to analyze this issue more deeply

**Comment by compwron** [comment]
We are still seeing this, but let's file it separately as it comes up.
