### ISSUE TITLE
Onboarding trackables not saved

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#324]
When a user signs up for Flaredown, the onboarding process does not save the trackables they choose, so they are forced to find them all again. It takes users a long time to find all of their trackables, so this is a big problem that makes many users quit.

To recreate: sign up for a new Flaredown account, go through the onboarding and choose trackables, then start today's checkin -- you'll see that none of the trackables you chose during onboarding are present and you have to add them all again.

**Comment by lmerriam** [comment]
@mpugach just discovered this high priority bug after users reported it -- since Kristine is out this week is it possible for you or someone else to help with it?

**Comment by mpugach** [comment]
will discuss with Alexander

**Comment by mpugach** [comment]
@lmerriam can you be more specific on recreate steps, please? It works in production and my dev environment also.
![flaredown-onboarding-480](https://user-images.githubusercontent.com/426179/28518165-a448fc52-706f-11e7-8cf0-cf4b6014ed3f.gif)

**Comment by lmerriam** [comment]
@mpugach Those are the exact steps I used, I recreated the issue both on development (my local machine) and production before I posted this. Multiple users also reported this issue, which is why I checked it.

Like you say, it's working well for me now. Very odd that I saw it on BOTH environments before.

**Comment by lmerriam** [comment]
Is it possible that there is a broader issue that is causing all of these strange bugs? Users are constantly reporting that new trackables aren't saved, that the app doesn't load, etc. Even on existing accounts that they've been using successfully for months--and sometimes the issues go away and come back repeatedly.

Maybe https://flaredown-errors.herokuapp.com/ has some clues?

**Comment by mpugach** [comment]
Top 3 errors are about the weathers logic. There are 2 external APIs involved. Geocoding and Weather. Seems like one of them does not have expected payload sometimes...

It can even prevent the creation of checkin, that is why some trackable data may not be saved.

Will rewrite the code to be more protective and see if it helps.

**Comment by lmerriam** [comment]
@mpugach Kristine mentioned this error, I think she suspected it too. It makes sense because it is external so could cause the issue on multiple environments!

**Comment by lmerriam** [comment]
@mpugach can we also make sure that if external dependencies like this fail, it won't take down the whole checkin/app? (maybe this is what you meant by "protective" already :)

**Comment by mpugach** [comment]
that is what I mean when write "protective code" :)

**Comment by mpugach** [comment]
deployed

**Comment by lmerriam** [comment]
@mpugach one of the users who reported the issue says it's working now, closing the ticket. Thanks for the help!

**Comment by mpugach** [comment]
great :)

It is not so critical, but there is no response to the user when geocoder fails to find a location by the postal code provided, I think @X-tina should implement it when she be back
