### ISSUE TITLE
Optional trackables

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#331]
As we add more trackables and integrations we can't assume every user will track all of them, so we should let them choose during onboarding. There are mandatory trackables that we want every user to track (conditions, symptoms, treatments and tags for now) and there are optional ones (weather, food) that should only be tracked if users want to.

- [ ] Allow the user to choose optional trackables in onboarding, after they select treatments
<img width="459" alt="screenshot 2017-07-30 17 14 46" src="https://user-images.githubusercontent.com/1657444/28757303-7b9545a8-754d-11e7-899d-d32e2b1c047c.png">

- [ ] Allow users to edit their optional trackables in the settings
<img width="356" alt="screenshot 2017-07-30 17 46 07" src="https://user-images.githubusercontent.com/1657444/28757347-fc0109ec-754e-11e7-80bb-2c2f95293b8e.png">

- [ ] Move weather and food to their own sections and restructure the checkin flow
<img width="945" alt="screenshot 2017-07-30 17 00 59" src="https://user-images.githubusercontent.com/1657444/28757302-7562a612-754d-11e7-9078-85c8ec2464f9.png">

**Comment by compwron** [comment]
Closing as old for now
