### ISSUE TITLE
Notifications getting stuck

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#332]
Notifications are not dismissing for some users, even after they have viewed them and clicked them. My account (logan@flaredown.com) is affected and users are getting the issue as well.

Video of the problem:
https://www.dropbox.com/s/lyzjkq5etmnd90u/bug_notifications_stuck.mov?dl=0

**Comment by X-tina** [comment]
@lmerriam 
Deployed on production

**Comment by lmerriam** [comment]
Seems to be resolved, have heard no reports and have not seen the issue myself 👍
