### ISSUE TITLE
Reevaluate ember-fastboot

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#333]
We need to decide whether we should redeploy fastboot or remove it entirely.

Criteria to redeploy fastboot:
1. Fast: the app should load quicker than without fastboot, and we shouldn't see issues like #314
2. Robust: we should not see new bugs
3. Performant: the app's resource usage should not increase dramatically. For example, when we first deployed fastboot it was averaging 600-800mb memory usage, compared to <10mb with it deactivated.

**Comment by X-tina** [comment]
- [ ] Pages load twice;
- [ ] Always routed back to login;

**Comment by compwron** [comment]
Closing as old for now
