### ISSUE TITLE
BUG: Users seeing data from other user accounts

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#347]
Report from a user:

>"I haven't used Flaredown in a while, but I've just logged back in and there seeemmms to be some weird entries in the 'journal' section - not sure what's happened there. Attached is screenshot. There are 7 entries in there, none of them are mine. Not sure if they're just 'sample data' or somehow another person's entries have got on my account. "

I can send the email of this user and another who reported this when needed.

**Comment by lmerriam** [comment]
Another user reports that they are seeing Foods that they have not tracked on their charts

**Comment by compwron** [comment]
Closing as old for now
