### ISSUE TITLE
Cache the history

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#35]
Right now, if the user leaves the history to navigate to another section of the app, then returns to the history, they have to load the history again. If possible, it would be ideal to cache the currently visible history when the graph loads, so that the user can quickly switch between sections of the app.

**Comment by mpugach** [comment]
@lmerriam check on staging

currently it uses cache only if user has enough checkins to cover visible range

**Comment by lmerriam** [comment]
Thanks Max! It seems to be working well, could you clarify exactly what you meant here:
> currently it uses cache only if user has enough checkins to cover visible range

**Comment by mpugach** [comment]
If the earliest checkin date is greater than visible start date then API call is preformed again. Same on other edge

**Comment by mpugach** [comment]
but the API calls are made with some room, so it tries to fetch more then visible

you can open the network tab in developer tools an play with it

the call look like this

![flaredown 2017-01-27 06-21-55](https://cloud.githubusercontent.com/assets/426179/22360535/3833e3da-e459-11e6-9a85-65af25f5d10a.jpg)

**Comment by lmerriam** [comment]
Gotcha, sounds good.

One thing I should have been more explicit about:

As part of caching I was hoping we could save the user's position and visible trackables in the history. So that if I switch to the check-in, then switch back the the history, I'll return to the same position with the same visible charts and we won't have to reload any data (plus user gets the benefit of not losing their settings)

Is this feasible?

**Comment by mpugach** [comment]
I think it is.

**Comment by mpugach** [comment]
deployed to staging

**Comment by lmerriam** [comment]
Works fantastic for me!
