### ISSUE TITLE
Unsubscribe bounced email addresses

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#359]
In order to maintain a healthy email account and to avoid being penalized by Amazon SES, we should capture complaints and bounces and make sure that we do not send further email to those addresses.

**Comment by lmerriam** [comment]
@X-tina this is live and working, correct?

**Comment by X-tina** [comment]
@lmerriam, yes, on staging. Can I deploy to production?

**Comment by lmerriam** [comment]
I don't know how to test :) so if you think it is ready to go then we can deploy.

This handles both bounces and complaints, correct?

**Comment by X-tina** [comment]
@lmerriam, yes, correct.
