### ISSUE TITLE
Hide and show trackables on history

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#36]
For simplicity, the first version of the history showed all trackables by default. That means it's tough for users to compare the specific trackables they're interested in (for example, if I want to see the effects of a particular treatment on a symptom, and they are not both visible on the screen). To fix this, let's give users control over the visible trackables.

<img width="654" alt="screenshot 2016-12-22 14 46 59" src="https://cloud.githubusercontent.com/assets/1657444/21442882/c3b2b7da-c855-11e6-9e21-45fbff36edaf.png">

- [ ] Button in the history navbar that lists the number of visible trackables, which you can tap on to open the trackable selector modal.
- [ ] Dropdown in the modal to select different trackable types. As we are adding new types of trackables, we should try to make sure that new ones in the future show up in this list.
- [ ] List trackables of the currently selected type, with a switch to turn them on/off in the history

**Comment by safeforge** [comment]
@lmerriam I'll start to work on this during the weekend, please provide some mockup when you've a chance.

**Comment by lmerriam** [comment]
Here's the mockups of the graph including some navigation updates: https://paper.dropbox.com/doc/Proposal-Flaredown-Patterns-Update-FdavPhtFHzkKFkP8xRxsu#:uid=573683640&h2=History-navigation-and-styles
