### ISSUE TITLE
Navigating patterns

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#361]
Users need to be able to view their patterns for time periods in the past in order to find correlations between trackables.

Requirements:
- [x] Display bottom bar with start/end dates and navigation arrows
- [x] Open the standard datepicker when the user taps the start or end dates
- [x] Update all patterns when the dates change
- [x] Do not allow user to enter a start date that is later than the end date or vice versa
- [x] Do not allow user to choose a date in the future

**If it is feasible**, we should add this enhancement:
- [ ] For time periods longer than 30 days, condense the datapoints on the chart into 7-day averages
- [ ] Show averaged numbers in the tooltip
- [ ] Arrows should navigate 20% of duration of the visible days (instead of 1 day)

**Comment by lmerriam** [comment]
@X-tina the first charts deploy was very good and I think I may have caused confusion with the last 3 bullet points above.

The "average numbers" idea should only apply if the user is viewing a very long period of time and we are condensing the chart so that it doesn't get too dense. Each point would become a week (instead of a day) and the value of that point would be the average values during that week. Here's an ugly mockup just to demonstrate the concept:
<img width="1171" alt="screenshot 2017-10-27 14 39 00" src="https://user-images.githubusercontent.com/1657444/32119884-9a0bbb94-bb24-11e7-967d-a4070931196d.png">

Your original version of the chart was very quick and worked perfectly, before I complicated things :). Can we roll this change back and consider those last three checkmarks as a separate ticket that we will add after we deploy the charts sharing?

**Comment by X-tina** [comment]
Ok, I'll rollback last points.

**Comment by compwron** [comment]
Closing as old for now
