### ISSUE TITLE
Sharing patterns via Email

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#363]
The first and easiest way to enable sharing is by allowing users to email a unique link.

Sharing dialog
![pattern - choose to share](https://user-images.githubusercontent.com/1657444/31319492-1ceb7c9a-ac32-11e7-841b-c95345ebb391.png)

Viewing a shared pattern
![view shared pattern](https://user-images.githubusercontent.com/1657444/31320141-70e85a42-ac3d-11e7-8e6c-4852d966bc93.png)

Requirements:
- [x] Display sharing dialog
- [x] Let the user choose one or more patterns to display
- [x] Generate unique link (ideally with a friendly shortened URL)
- [x] Tapping "Share via email" button should open a `mailto` link with the unique URL in it
- [x] For privacy, it should not be possible for a third party to find new share links based on the unique URL

**Comment by X-tina** [comment]
@lmerriam 
- Where should I display a sharing dialog page?
- Could you provide a mockup for more amount of patterns
