### ISSUE TITLE
Native mobile push notifications

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#370]
Users would prefer to receive notifications to the device, rather than emails that clutter up their inbox. We can set up the mobile apps to send the necessary device identifiers to a push service, but we need an API endpoint and some interface for settings on the web side:

- [ ] Create an endpoint for registering a device (accept device identifiers)
- [ ] Set up a worker to push check-in reminders and chat notifications (new replies) to users' devices
- [ ] Use the same interface in settings and onboarding that we are currently using for email reminders and chat notifications
- [ ] Only show the push notification option if the user has registered a device

**Comment by compwron** [comment]
Closing as old for now

**Comment by benlangfeld** [comment]
@compwron Logan mentioned this on our call today as a top request from users. Is it worth re-opening as a marker for that?
