### ISSUE TITLE
Send userbase to Sendy

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#373]
I've set up Sendy (www.sendy.com) in order to make emailing easier to manage. We should add all users so that we can send welcome and update emails.

- [ ] Send all current user accounts to Sendy
- [x] When new users sign up, push their account data to Sendy
- [x] Record the `signup date` and the `last checkin` date as custom fields on each user (any time there is a new checkin, update the `last checkin` field for that user in Sendy

**Comment by compwron** [comment]
Closing as old for now
