### ISSUE TITLE
Remove "unsaved changes" message on Checkin's first screen

### ISSUE THREAD

**Issue by algodave** [rubyforgood/Flaredown#39]
![flaredown 2016-03-30 15-16-02](https://cloud.githubusercontent.com/assets/2955556/14143280/b4715d64-f68a-11e5-9f2c-69735de49534.png)

The message stays there because autosave isn't triggered on the first screen. I need to investigate about why the Ember record is dirty at that point, but anyways I don't think we need such message at all on this screen. @lmerriam Do you agree?

**Comment by lmerriam** [comment]
Fully agreed @algodave !

**Comment by lmerriam** [comment]
In fact, I'm adding this to Launch because it could be pretty confusing and should be high priority
