### ISSUE TITLE
Allow user to change their email

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#397]
Currently, users can't change their account email (or even see it). We should allow them to do so in the settings, similar to how they currently change their password.

**Comment by compwron** [comment]
![Screen Shot 2021-10-08 at 4 59 21 PM](https://user-images.githubusercontent.com/578159/136636229-8a84d1c2-51d8-4def-b37b-1c2b1584d169.png)
Closing as done
