### ISSUE TITLE
Improvements to /signup

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#398]
Move the birth date field to the first signup page and show an error message if the user inputs an age below 16. We need to make sure users explicitly accept our terms and privacy. We also have many users who see the "username" field and are concerned about privacy, so we should clarify what the username is for.

- [x] Add date of birth field to /signup
- [x] Remove date of birth from it's current place
- [x] Error: "You must be 16 years or older to use this app according to international privacy regulations. Sorry :("
- [x] Add note under username label: "Other users will never see your data. Your username will only be displayed if you choose to post in the Flaredown chat."
- [x] Add checkbox: "Accept the Terms of Use and Privacy Policy" with links to each document
- [x] Change page header and submit button text to match wireframe

**Comment by lmerriam** [comment]
![desktop](https://user-images.githubusercontent.com/1657444/41666599-d78eb0bc-7478-11e8-8e87-740be336ccc4.png)

**Comment by compwron** [comment]
These changes seem done.
