### ISSUE TITLE
Change "your daily digest" text

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#399]
Some users don't understand "Daily digest". We should change this text to "topics you might like".

- [ ] Change text to "Topics you might like"

**Comment by lmerriam** [comment]
<img width="508" alt="screenshot 2018-06-20 10 35 44" src="https://user-images.githubusercontent.com/1657444/41666187-e412eebc-7477-11e8-91bf-b66f06dea54f.png">

**Comment by compwron** [comment]
This page does not currently load, but once it does, this change will be nice to have.
