### ISSUE TITLE
Apps are down, certs ok?

### ISSUE THREAD

**Issue by kautzz** [rubyforgood/Flaredown#405]
My wife is unable to use the android app or the web app of flaredown. Android even pulled it from their stores?! Might this be caused by an expired cert?

**Comment by compwron** [comment]
Unfortunately, the site is having some troubles. If you have time to help try to fix it, please sign up. :( http://flaredown.com/notice.html

**Comment by kautzz** [comment]
Uhhh noes @compwron 
Unfortunately I'm not much of a web dev and currently pretty busy supporting my wife. 
Is there a plan to action or todo list somewhere that I might check to see if I can help out?

**Comment by compwron** [comment]
@kautzz Flaredown is back up! You can log in and view your data at https://app.flaredown.com/
We are working on getting the app back into the app store. For now you can use the app from your phone or computer by visiting https://app.flaredown.com/

Your help would be very much appreciated! Currently we are coordinating work in the #flaredown channel of https://rubyforgood.herokuapp.com/ and we would love to have your help!

**Comment by kautzz** [comment]
@compwron sweet, thanks for letting me know. My wife will appreciate your work. I'll check out the channel and see how I might help after work. See you in a bit.
