### ISSUE TITLE
webapp signup not working - reCAPTCHA invalid domain for site key

### ISSUE THREAD

**Issue by kautzz** [rubyforgood/Flaredown#408]
When trying to sign up for flaredown through the webapp on https://flaredown-webapp.herokuapp.com/signup the reCAPTCHA is not working so that registering a new account is not possible.

![Screenshot from 2021-02-02 20-40-43](https://user-images.githubusercontent.com/5493156/106653357-faabe080-6596-11eb-9bfc-000f5d673880.png)

**Comment by lmerriam** [comment]
You'll want to use the public url: app.flaredown.com/signup

**Comment by kautzz** [comment]
> You'll want to use the public url: app.flaredown.com/signup

Yes, that works. Was using the URL provided in the slack channel details ;)
