### ISSUE TITLE
ids param sent as object rather than as array to treatments endpoint

### ISSUE THREAD

**Issue by algodave** [rubyforgood/Flaredown#46]
This is what's causing the following:
https://flaredown.airbrake.io/projects/121837/groups/1653854108580241014/notices/1653854106619961672

Here's the params:

``` json
{
  "action": "index",
  "controller": "api/v1/treatments",
  "format": "json",
  "ids": {
    "0": "4544",
    "1": "9213"
  }
}
```

`ids` should be an array, it is an object instead because the query string is `?ids[0]=4544&ids[1]=9213`

@safeforge Any idea?

**Comment by safeforge** [comment]
@squiggie It seems that the following params: `?ids[0]=4544&ids[1]=9213` sent to the `treatments` endpoint are causing a database error.

Please note that ids should be an array, so no indexes inside square brackets. I’m implementing a better exception handling, however let me know in case it’s an issue for your client to send an array
