### ISSUE TITLE
Chat/discussion feature is broken

### ISSUE THREAD

**Issue by bklang** [rubyforgood/Flaredown#480]
The loading icon (see attached) appears forever.  We should either fix or hide this feature.
![Screen Shot 2021-10-12 at 2 09 06 PM](https://user-images.githubusercontent.com/167131/137007727-03745f81-f960-43da-89dd-73cbd51fd4c8.png)

**Comment by bklang** [comment]
The PR addressed code issues (likely introduced by our recent upgrade work), but the chat feature still does not work in staging. The reason is that the tier of MongoDB to which we subscribe does not allow the `mapReduce` feature. You can see this in the API response: `[8000:AtlasError]: CMD_NOT_ALLOWED: mapReduce (on 2flaredown-staging-lind-shard-00-02.ql1v6.mongodb.net:27017)`. The restriction is mentioned [in the MongoDB service documentation](https://docs.atlas.mongodb.com/reference/unsupported-commands/)

I can think of two options at the moment:
* Upgrade to at least an M10 instance with MongoDB, which would cost somewhere around $60/mo
* Refactor the queries to avoid `mapReduce`. This happens in [two](https://github.com/rubyforgood/Flaredown/blob/5d06634fe7f5ee750ecca34594662a11137475d9/backend/app/models/reaction.rb#L42) [places](https://github.com/rubyforgood/Flaredown/blob/5d06634fe7f5ee750ecca34594662a11137475d9/backend/app/models/notification.rb#L81) right now.

**Comment by benlangfeld** [comment]
> The PR addressed code issues (likely introduced by our recent upgrade work), but the chat feature still does not work in staging. The reason is that the tier of MongoDB to which we subscribe does not allow the `mapReduce` feature. You can see this in the API response: `[8000:AtlasError]: CMD_NOT_ALLOWED: mapReduce (on 2flaredown-staging-lind-shard-00-02.ql1v6.mongodb.net:27017)`. The restriction is mentioned [in the MongoDB service documentation](https://docs.atlas.mongodb.com/reference/unsupported-commands/)
> 
> I can think of two options at the moment:
> 
> * Upgrade to at least an M10 instance with MongoDB, which would cost somewhere around $60/mo
> * Refactor the queries to avoid `mapReduce`. This happens in [two](https://github.com/rubyforgood/Flaredown/blob/5d06634fe7f5ee750ecca34594662a11137475d9/backend/app/models/reaction.rb#L42) [places](https://github.com/rubyforgood/Flaredown/blob/5d06634fe7f5ee750ecca34594662a11137475d9/backend/app/models/notification.rb#L81) right now.

You know, I'd love to know why we're using Mongo for this rather than Postgres. I havn't looked into it, so from the code it might be obvious, but it should probably be mentioned at a high level in the readme. There's a chance that what feels like it should be relational data could be much more performantly handled in a relational database.

We should at least be careful not to pull huge computations into the Rails process and blow out memory consumption there.
