### ISSUE TITLE
Landing page shows old app UI and does not take advantage of desktop screens

### ISSUE THREAD

**Issue by bklang** [rubyforgood/Flaredown#493]
We want to propose a new landing page for Flaredown.com that adapts to mobile & desktop views, and also reflects the current state of the application. This issue tracks that work

**Comment by samanthar8** [comment]
I converted a card on the project to [an issue](https://github.com/rubyforgood/Flaredown/issues/500) for the same thing. 

As I added more details to the other issue, I'm closing this one.
