### ISSUE TITLE
Questions for Logan

### ISSUE THREAD

**Issue by bklang** [rubyforgood/Flaredown#494]
Creating this issue to track the questions for our 11am meeting with @lmerriam, as well as the responses to those questions

- [x] Opinion on #481
- [x] #450
- [x] #449
- [ ] Where can we get iOS credentials for releasing an update to the mobile app?
- [ ] Where does the current, official Android app live? It does not seem to match what we see in Github?
- [x] The chat/discussion feature in the app is broken - prefer fixing or removing?
- [x] Opinion on #406
- [x] Thoughts on the [home page refresh](https://rubyforgood.slack.com/files/U01BKPBNC7J/F02J8JMCZ24/desktop_-_1.png)? - Where does the code for the landing page live? Where is it deployed to?
- [x] Thoughts on the logo redesign?

**Comment by samanthar8** [comment]
To-dos:
- [x] @benlangfeld  - send whatever Logan needs for the DNS entry
- [ ] @lmerriam - send iOS / Android credentials when received from original developers

**Comment by benlangfeld** [comment]
@samanthar8 www. already works as per that issue. I had just suggested also forcing TLS (in the github repo config).

**Comment by bklang** [comment]
Thanks for a great week! We'll close this out for now - any future discussion will happen on the relevant issues & PRs.
