### ISSUE TITLE
Weather API is end-of-life

### ISSUE THREAD

**Issue by bklang** [rubyforgood/Flaredown#535]
From [this blog post](https://blog.darksky.net/):

> Update: Support for the Dark Sky API service for existing customers will continue until the end of 2022. The iOS app and Dark Sky website will also be available until the end of 2022.

It's not possible to get an API key to test weather features locally, and soon(ish) it will break for the live site too. A replacement needs to be found.

**Comment by compwron** [comment]
This is coming up again- USA zip code getting South Korea weather.

**Comment by compwron** [comment]
https://openweathermap.org/price free tier should work for us.
![Screen Shot 2022-01-04 at 11 49 23 PM](https://user-images.githubusercontent.com/578159/148180134-41bef9db-3c9e-4563-befa-1492435d70a7.png)
 
 
 I signed up for an account for flaredown so we have an API token now
API docs
 https://openweathermap.org/current
 Call current weather data for one location
By city name
By city ID
By geographic coordinates
By ZIP code
```
api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}
```
