### ISSUE TITLE
Some trackables not being removed from check-in

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#54]
Yesterday I removed several symptoms from my check-in, and they returned today. Curiously, the treatment changes I made were saved correctly. I have been hearing reports of trackables not being removed from other users as well.

**Comment by algodave** [comment]
Currently, trackables are "untracked" (meaning, you won't get them the next day) only when you work on today's checkin. Let me know if we need to change that behavior

**Comment by lmerriam** [comment]
Yes that's the behavior I'm referring to. Right now if I remove a trackable on today's checkin it sometimes returns the next day.

**Comment by lmerriam** [comment]
I am sorry I don't have reliable steps to reproduce :\ It may be that it only happens on migrated trackables, as I haven't yet seen it happen for anything I added after getting on the new app.

**Comment by algodave** [comment]
@lmerriam If you provide me the name of the trackable and the checkin day when you removed it, I can investigate in the logs

**Comment by lmerriam** [comment]
Yesterday I successfully removed "test" and "chilly finger" after trying on at least one prior day to remove them.

**Comment by algodave** [comment]
@lmerriam 
I've made some checks on data and here's what I see:
- you untracked a symptom named "test" on 2016-04-04 11:48:26 UTC
- you untracked a symptom named "chilly finger" on 2016-04-04 11:48:27 UTC

which basically confirms what you said in your previous comment.

There was something wrong with the autosave logic which prevented "untrack" API to be invoked in some cases. I think that was the issue, 'cause I deployed the new save logic on 2016-04-03 in the evening my time.

I would close this issue, please reopen should you see it again.

**Comment by lmerriam** [comment]
:+1:
