### ISSUE TITLE
Graph: visible trackables

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#55]
Only trackables that were in the user's check-in during the current graph time window should be visible in the graph.

**Comment by algodave** [comment]
Currently, the graph shows trackables that the user is tracking on the current date.

**Comment by lmerriam** [comment]
Correct, but it should be based on the viewport--meaning if I go back in time two weeks I should see what I was tracking two weeks ago, not what I am tracking today. You can see an example by moving around in the graph on the old app.
