### ISSUE TITLE
Accept the terms sign up checkbox misplaced

### ISSUE THREAD

**Issue by AlysonBasilio** [rubyforgood/Flaredown#599]
The CTA "I accept the Terms..." on the sign-up page is misplaced.
![image](https://user-images.githubusercontent.com/2593231/197525048-33e2ad82-b08a-4650-885c-03af57814d3d.png)

Btw, I would like to contribute to the project 😄

**Comment by compwron** [comment]
thanks for opening this issue! we appreciate it :) Can you work on fixing it also? :)

**Comment by AlysonBasilio** [comment]
Of course! I will be working on it.
