### ISSUE TITLE
Download CSV

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#63]
Add a button called "Download data" in the account dropdown that allows the user to download a CSV with all of their data.

For the user, I believe the best format is:
- One column for each trackable_name
- One row for each date that they checked in

**Comment by mpugach** [comment]
Can it be "Send me the data"?

Because export can take some seconds, so:
1. user will stair at the monitor and wait something to happen
2. web server will waste the connection for long running response

We can process this asynchronously instead. And send the result with email. This will require a sidekiq heroku worker.

**Comment by lmerriam** [comment]
This would be much better! I was actually going to ask you if this was an option, as most of our users are on mobile and would have trouble using the resulting CSV if it went directly to their device.

I assume the sidekiq worker is pretty inexpensive to run if we assume, for example, 100 downloads per day in total (I think that's 20x what we'll actually see).

**Comment by mpugach** [comment]
Can you provide the email subject and text please?

**Comment by lmerriam** [comment]
Subject:
"Your Flaredown data is here"

Body:
"You'll find your Flaredown data attached in CSV format. We hope it helps!

 \- The Flaredown Team"

**Comment by mpugach** [comment]
@lmerriam check please

**Comment by lmerriam** [comment]
Works flawlessly for me! Ready to deploy

**Comment by mpugach** [comment]
Then activate please one worker dyno on heroku. Or I can do it, just need your confirmation, since it costs 25$/month
