### ISSUE TITLE
Unable to remove trackable added by mobile app

### ISSUE THREAD

**Issue by squiggie** [rubyforgood/Flaredown#70]
Whenever a trackable is added via the mobile app, if you then visit the web app and try to remove that trackable, the UI will remove the item, but the message at the top will continue to say "you have unsaved changes" and if a page reload happens, the trackable is still there. 

Please see checkin https://staging.flaredown.com/checkin/5744659374e2db0003000001/summary for en example.

**Comment by algodave** [comment]
@squiggie I have no permission to see your checkin in the app. Could you please try again while keeping the developers console open in your browser, and then post a screenshot here with the errors in both Console and Network tabs? Thanks

**Comment by lmerriam** [comment]
@squiggie is this still happening?

**Comment by squiggie** [comment]
I will have to check again. I believe adding trackables from the mobile app was broken on our last refactor so we'll have to get that working again. I will update once we have it working and can test.

**Comment by lmerriam** [comment]
Closing for now
