### ISSUE TITLE
"Minimum version" API endpoint for mobile

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#72]
We need an endpoint that the mobile app can hit and will return the current "minimum version" so that we can force users to upgrade their app if needed. @thunter1000 can answer clarifying questions

**Comment by algodave** [comment]
@thunter1000 Can you paste the old endpoint URL and returned data format?

**Comment by thunter1000** [comment]
@algodave The old endpoint was `minimumClient`.... The json it returned was the following:

```
{
   "ios":{
      "major":0,
      "minor":0
   },
   "android":{
      "major":0,
      "minor":0
   },
   "locales":1
}
```

The locales attribute can be removed, as they are no longer provided by the api.

The old implementation can be found here:
https://github.com/Flaredown/FlaredownAPI/blob/0053da6ac3f59a3243952673949026c648e16f3d/app/controllers/application_controller.rb#L21

**Comment by algodave** [comment]
@thunter1000 You can test it on staging:
https://flaredown-staging-api.herokuapp.com/api/minimum-client

**Comment by thunter1000** [comment]
@algodave Yes this works perfectly, thanks

**Comment by algodave** [comment]
Now on production:
https://app.flaredown.com/api/minimum-client
