### ISSUE TITLE
Upgrade to Rails 7

### ISSUE THREAD

**Issue by haydenrou** [rubyforgood/Flaredown#734]
There is currently two PRs open to tackle this but they haven't been touched for a while. This could be done together with https://github.com/rubyforgood/Flaredown/issues/710

Current PRs:
- https://github.com/rubyforgood/Flaredown/pull/650
- https://github.com/rubyforgood/Flaredown/pull/640

You could either work off of these or start fresh. Either way, make sure to update those PRs with a comment.

**Comment by thejonroberts** [comment]
I'm working on this, and I think I'm almost done. Going to open a draft PR, comment on the other PRs.
