### ISSUE TITLE
Support Android WebView Notifying Page Change

### ISSUE THREAD

**Issue by thunter1000** [rubyforgood/Flaredown#74]
The android application is going to use a web view to temporarily display parts of the site which have not been implemented natively on the android app. In order to do this android needs notifying when a page changes. To do this android can implement a global variable as an interface for an example go here https://developer.android.com/guide/webapps/webview.html and scroll down to the "Binding JavaScript code to Android code" title. I will let you decide on the variable name, as this does not affect me much. So something like `MobileInterface.onPageChange("the new url address")`.

**Comment by algodave** [comment]
@thunter1000 Here's the relevant line from my commit above:

`AndroidInterface.pageChanged(document.location.href);`

You can test it on https://staging.flaredown.com/

**Comment by algodave** [comment]
This is on production as well. Closing
