### ISSUE TITLE
Treatments rearrange when turned on

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#77]
Clicking the switch to "turn on" a treatment causes the treatment to rearrange itself in the list

**Comment by algodave** [comment]
@lmerriam What about always showing treatments and other trackables in alpha order? In both checkin steps and summary.

**Comment by lmerriam** [comment]
How about newest-added at the top, is that an easy ordering?

**Comment by algodave** [comment]
@lmerriam We're not currently storing date added on each individual checkin trackable. 

I think the most flexible solution would be to store a `position` column and let users re-order trackables via drag'n'drop (we could have some spot in a trackable row where the cursor becomes 2 crossed arrows which users can click and drag). 

The default behavior when users add a new trackable could be to set the `position` to `max+1`, and show trackables sorted by position `DESC`, so that we would end up having newest-added at the top

**Comment by lmerriam** [comment]
That would be excellent -- it's actually a highly requested feature

**Comment by algodave** [comment]
@lmerriam Cool, do you have some hints for the UI?

**Comment by algodave** [comment]
@lmerriam My proposal is to design a tiny light button at the beginning of each row (left side) with an `fa` icon in it. For example:
- `fa-ellipsis-v` - my favourite: simple and not too eye-catching
- `fa-sort` - my second choice
- `fa-reorder` - too common IMO
- `fa-arrows` - too noticeable and somewhat "old school"

What do you think? Any better idea?

**Comment by lmerriam** [comment]
@algodave let's use fa-ellipsis-v, and let's make sure it works well on mobile

**Comment by algodave** [comment]
@lmerriam While developing the feature I actually changed my mind about adding the `fa-ellipsis-v` visual hook for dragging. The solution you can now test on staging doesn't add any new visual element. Just click (tap) on a trackable's area and move it up or down: that's it!
I've tested it on Android Chrome and iOS Safari and works pretty well. 
To scroll on mobile, users should use the whitespace on the right side of trackables. 
However, to avoid drag'n'drop colliding with scroll actions on mobile, I was thinking we could have some global toggle per each trackable group to enable/disable drag'n'drop. Open to any other suggestion here of course!

Another enhancement that I guess should be done is remembering positions from the current day to the next, can you confirm?

Looking forward for your feedback!

**Comment by lmerriam** [comment]
@algodave it works great on my computer and phone!

Only issue is that I can't seem to drop a trackable in the first or last place in the list, which means when I have two trackables I can't reorder them. This occurs with mouse and touch for me.

I totally understand the idea of dragging the whole trackable but I think we need a specific visual element. Users are going to scroll the page 100 times more often than they will rearrange the trackables, so the scrolling needs to be the easy. And I don't think we'll ever get users to change their scrolling habits just for our check-in.

Does that make sense? Don't worry about making it look good, you can drop the icon in wherever and I'll figure out where to put it and commit some style updates.

**Comment by lmerriam** [comment]
One other thing to think about: I've learned that our users have crazy long lists of trackables, much longer than the screen height. If there's an easy way to make the screen scroll when I drag a trackable to the top or bottom of the screen that would be helpful! But definitely not worth worrying about if it's going to take hours of dev time, as users can already rearrange anywhere by dragging multiple times.

**Comment by algodave** [comment]
@lmerriam Moving to first place actually works; whereas moving to last place could be achieved in 2 moves: 1) moving down to n-1 position, 2) moving up the last element by 1 position. Of course I can figure out that and fix.

**Comment by lmerriam** [comment]
You're right, moving to first place works for me too!

Also I just noticed that scrolling I mentioned already works on desktop, just not my android phone.

**Comment by algodave** [comment]
Hey @lmerriam you didn't provide me feedback about this suggestion I posted yesterday:

> Another enhancement that I guess should be done is remembering positions from the current day to the next, can you confirm?

**Comment by lmerriam** [comment]
@algodave yeah it would be best if it remembered positions day-to-day

**Comment by algodave** [comment]
@lmerriam On staging you can now test an updated version with the following changes:
- Trackables can now be dragged down to the last position
- To enable drag'n'drop on mobile, simply click on a trackable's title: it will be highlighted with a dashed border and will become draggable

It seems a pretty usable solution to me, let me know what you think of it!

**Comment by algodave** [comment]
@lmerriam With the above changes, trackables positions are now remembered from today to tomorrow.
