### ISSUE TITLE
Doses not being remembered

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#81]
Two users have recently emailed to say that their doses are not being remembered effectively

**Comment by lmerriam** [comment]
@algodave i tagged you in a conversation with one of the users, she provided good data

**Comment by algodave** [comment]
I've made some refactoring/improvements to address this:
- 3820cb89adc3a40ac2abca5f4c01a84dac5e9f7d
- 92d28e06de82ed3c4a31cdbada7fa0e26d652739
- 7be2edf0035cf1c2c9deb3344dc7095efd693ead
- bb9348030ac4d412444d407b84449683b9c8fff4

Improved doses dropdown can be tested on staging, @lmerriam please try it out.

**Comment by lmerriam** [comment]
LGTM 👍
