### ISSUE TITLE
Add trackable: make first result "Start typing..."

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#83]
Users are still looking at the select2 for adding trackables as a dropdown only and complaining that they "only see a few results starting with A"

Before someone has entered the first character, let's make the top result "Start typing..." to indicate that they should be searching for their trackable

**Comment by algodave** [comment]
@lmerriam I'm not sure that would be a good solution. The top result is "Add <Text Typed>" because if it's chosen, the typed text gets added as a new trackable. If we change it to "Start typing..." it might be ok for when users actually find the desired trackable in the dropdown, but it won't be ok when they don't, and want to insert their custom one.

I suggest the following changes:
1. Change placeholder to "Start typing a {Condition | Symptom | Treatment}..."
2. Style the select to make it appear like a text input
3. Don't preload any trackable in the dropdown until the first character is typed

I think the above 3 changes should stimulate users to type some chars before choosing. What do you think?

**Comment by lmerriam** [comment]
Oh totally, I should have made this part more clear:

> Before someone has entered the first character

It should only show "start typing" until they have actually started typing, at which point it would change to "add xxx". I think this is a good solution.

**Comment by lmerriam** [comment]
@algodave this is high priority, I see almost every user misinterpreting this. Here's a mockup, I also tweaked the "Add xxx" formatting to make it look like the other results because users aren't realizing that the smaller grey version we have now is selectable.

Curious to hear your thoughts on the two options in the second step

![artboard 39](https://cloud.githubusercontent.com/assets/1657444/16392047/f214ddb6-3c77-11e6-8541-e95c9ccabf73.png)

**Comment by algodave** [comment]
@lmerriam I had already started on this and have pushed to staging what I've done so far. See   aeca71c commit comment above for a summary of changes. About the "Add xxx" item, I have no control on its HTML as it's created by `selectize.js`'s internal code, but I've been able to improve its readability through CSS.
I think the above changes make anyways a considerable improvement in usability, please try them on staging and let me know thoughts.

**Comment by lmerriam** [comment]
Ok cool I see the updates. I definitely want to keep the darker "Add xxx" because that makes it look more clickable. But I think we should revert these two things:
- The placeholder text should revert to "Add a tag" because if it says "Start typing a tag" before the user clicks into the input they won't know what the field is for. However if we could change to "Start typing a tag" once the user has focused the field, that would be the best
- The user should see autocomplete options when they click in, even before typing, as it does now on production. It gives them an idea of the sort of things they can start typing, even if their trackable is not in that list. I've tested this a bunch of times and always found it to be super helpful to users.

One thing that will help a lot is to remove the "..." at the end of "Add xxx..." because it doesn't make sense in this context. It should just be "Add xxx", that might be causing some of the confusion.

Why can't we change the "Add xxx" to look like the rest of the results? Is it some default selectize option? Not a big deal, we can find another way around it, but I'm curious.

**Comment by algodave** [comment]
@lmerriam All changes discussed can now be tested on staging. To recap:
- dropdown placeholder changes on focus
- "Add XXX" top element fully customized
- initial ten items loaded randomly

**Comment by lmerriam** [comment]
It's fantastic! I'm closing 👍
