### ISSUE TITLE
Mobile menu doesn't dismiss when navigating

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#90]
To reproduce: open the menu, click a page to navigate to, note that the app navigates in the background but the menu doesn't dismiss

See an example here: https://www.fullstory.com/ui/1E6EM/session/5705241014042624:5705241014042624!5629499534213120:1467046723196

**Comment by algodave** [comment]
First thing I did was adding the following event handler in `navigation-bar` 's [installHandlers()](https://github.com/Flaredown/FlaredownEmber-2/blob/master/frontend/app/components/navigation-bar.js#L12) method:

``` javacript
      this.$('.sliding-panel-content ul li a').on('click touchstart', (e) => {
        this.$('.sliding-panel-content,.sliding-panel-fade-screen').removeClass('is-visible');
      });
```

It worked everywhere except on iOS Safari: what happens there is the above handler prevents Ember actions to be triggered! I've been debugging and googling a lot to figure out why that happens as I have no errors in console, but couldn't find anything.

What I'll do then is implement another solution: 
- remove the `is-visible` class on each individual action
- for menu items triggering a route transition, hook `didTransition()` in `router.js` and remove the `is-visible` class from there.

/cc @safeforge

**Comment by algodave** [comment]
I actually preferred to avoid putting that logic in `router.js`, so I created ad-hoc actions in `navigation-bar` component for:
- transitioning to chart page
- opening discourse page in new tab

@lmerriam Can be tested on staging
