### ISSUE TITLE
Prompt for start and end dates of trackables

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#93]
![Adding a trackable](https://cloud.githubusercontent.com/assets/1657444/17794288/15051e26-657c-11e6-8a47-407391050311.png)

![Removing a trackable](https://cloud.githubusercontent.com/assets/1657444/17794397/00887e2e-657d-11e6-9ae5-5fa512e1b50b.png)

**Comment by lmerriam** [comment]
Question: there could be complications if a user tracks something for a month, then stops it, then later starts again. Can the system keep track of multiple different "periods" of tracking the same thing?

**Comment by algodave** [comment]
@lmerriam It's not an issue to the system to keep track of multiple different "periods" of tracking the same thing. It already acts like this if you delete a trackable on _today's_ checkin and then add the same trackable again some days later.
The data model is ready for this change, it's merely a frontend change plus minor API adjustments

**Comment by lmerriam** [comment]
Ok! In that case I think we just need to adjust the text a bit to show the user that the specific period they are ending. For example "This will be considered the last day that you tracked Crohn's Disease for the period starting May 1, 2015"

Does that make sense?

**Comment by compwron** [comment]
Closing as old for now
