### ISSUE TITLE
Allow user to delete account

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#95]
When users leave the platform they often want to make sure that their personal information is wiped. We should add a button under settings to allow them to remove their private information and close their account so we do not have to do it manually.

- [x] Add a link in settings
- [x] Create a page for account deletion
- [x] Ask the user for feedback
- [x] Suggest that the user download their data before they delete their account
- [x] Remove: email, password, username, birth date, area code (from weather)

**Comment by mpugach** [comment]
should we keep the tracked data for statistics since it has no identification?

**Comment by lmerriam** [comment]
Ask user for reason to delete account.

**Comment by lmerriam** [comment]
<img width="595" alt="screenshot 2018-06-19 17 24 08" src="https://user-images.githubusercontent.com/1657444/41625086-9580fad8-73e5-11e8-9112-777a83e80552.png">

**Comment by X-tina** [comment]
@lmerriam  Do I need to remove user from DB or just deactivate him?
Area (postal) code is stored in the Position model which has reference to weather model and it doesn't linked to the user itself. So can we keep it ? This could decrease the request amount to DB. Because many users could have the same  postal code.

**Comment by lmerriam** [comment]
@X-tina to clarify: we should not remove the postal code itself (as you say, other users depend on it) but we should remove the deleted user's **reference** to the code.

Even though multiple users may have the same postal code, US privacy regulations say that any location more specific than Country is considered personally identifiable information, and we need to remove all personally identifiable info for users that choose to delete their accounts.

**Comment by X-tina** [comment]
@lmerriam 
There is a reference in the checkin model for encrypted_user_id by position. I'll remove data from this attribute.

**Comment by compwron** [comment]
This is done
