### ISSUE TITLE
"Overall well-being" and "having a flare" trackables

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#97]
Replaces the current Start screen:
<img width="909" alt="screenshot 2016-08-18 21 46 10" src="https://cloud.githubusercontent.com/assets/1657444/17796226/3536f258-658d-11e6-9ade-f59f92b65aa0.png">

**Comment by lmerriam** [comment]
Smiley graphics here: https://www.dropbox.com/sh/1uph1ir8p8wx9oo/AABxyCBlWNuqp1UKzziUFzPAa?dl=0

**Comment by compwron** [comment]
Closing as old for now
